### ISSUE TITLE
Feature Request: Option to ignore ENOENT in checkRootPathForErrors

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify-static#101]
The `npm start` for one of my web apps runs a fastify server which uses fastify-static twice:
```js
fastify
  .register(fastifyStatic, {
    prefix: '/dev/',
    root: path.resolve('src')
  })
  .register(fastifyStatic, {
    prefix: '/app/',
    root: path.resolve('dist')
  })
```
The `src` directory always exists, this is the unmodified source.  `dist` may or may not exist, it is the product of `gulp build`.  Right now I use `fs.mkdirSync(path.resolve('dist'), {recursive: true})` before initializing the fastifyStatic plugin to suppress the `"root" path "${rootPath}" must exist` error.  It would be nice if I did not have to force creation of the empty folder for this to work, just let normal 404 logic deal with ENOENT at request time.

Are you open to this?

**Comment by mcollina** [comment]
The reason why it is currently throwing is to avoid typos. A simple typo could be very hard to debug - and I make a lot of typos. I’m ok in logging with a warn level instead.

**Comment by coreyfarrell** [comment]
I have code prepared to make that change but I'm having trouble figuring out how to monitor the pino logger to verify the warning from testing, right now it's just printing to stdout.

**Comment by coreyfarrell** [comment]
I figured it out.  I was confused and I thought `destination` was an option, not it's own argument.
