### ISSUE TITLE
Use wildcard to pass a custom globPattern

### ISSUE THREAD

**Issue by AndersCan** [fastify/fastify-static#106]
Hi

What would you think about using the `wildcard` option to set the globPattern? 

I'm thinking that `wildcard` can be set to a string, for ex: `**/*.{js,json}`, and then be used instead of the default `**/*`

[I've created a fork with the change](https://github.com/fastify/fastify-static/compare/master...AndersCan:master) and am open to any suggestions or changes required.

Thanks

**Comment by mcollina** [comment]
That looks good! Would you like to send a PR?

**Comment by AndersCan** [comment]
Done! https://github.com/fastify/fastify-static/pull/107
