### ISSUE TITLE
async style not supported

### ISSUE THREAD

**Issue by markrzen** [fastify/fastify-static#110]
## 🐛 Bug Report

When async style is used, undefined promise error is always logged.
Originally filed in as [help issue 106](https://github.com/fastify/help/issues/106)

## To Reproduce

Change the example in in project to use async and watch logs.

```js
'use strict';

const path = require('path');
const fastify = require('fastify')({ logger: { level: 'trace' } });

fastify
  .register(require('../'), { root: path.join(__dirname, '/public') })
  .get('/', async (request, reply) => {
    reply.sendFile('index.css');
  });

fastify.listen(3000, err => {
  if (err) throw err;
});
```

## Expected behavior

No promise undefined error to be logged as per [Promise resolution](https://github.com/fastify/fastify/blob/master/docs/Routes.md#promise-resolution) documentation.

## Your Environment

- *node version*: `12.7.0`
- *fastify version*: `2.8.0`
- *os*: `Mac`

**Comment by mcollina** [comment]
What's the current output? If `index.css` is not existing, you should be getting a 404.

**Comment by StarpTech** [comment]
The issue here is that an error is logged because `sendFile` doesn't accept a callback or return a promise. The route is fulfilled to `undefined` before the file was sent.

**Comment by markrzen** [comment]
As @StarpTech mentioned the current output is correct, it is the side effect of getting an error in the log that is the issue.

```
FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204
```

**Comment by StarpTech** [comment]
I tink the easiest fix is to pass an optional [`"end" event-handler`)[https://github.com/pillarjs/send#events] to the `pumpSendToReply` function so that the function can be promisifyied.

**Comment by StarpTech** [comment]
After release of https://github.com/fastify/fastify/pull/1869 you can await the `reply` object.

**Comment by stephan9mertel** [comment]
Any update on this? Will it be fixed in some future release?

**Comment by mcollina** [comment]
It's already in fastify:

```js
'use strict';

const path = require('path');
const fastify = require('fastify')({ logger: { level: 'trace' } });

fastify
  .register(require('../'), { root: path.join(__dirname, '/public') })
  .get('/', async (request, reply) => {
    reply.sendFile('index.css');
    return reply; // this does the trick
  });

fastify.listen(3000, err => {
  if (err) throw err;
});
```

**Comment by stephan9mertel** [comment]
Thanks a lot @mcollina!

**Comment by markrzen** [comment]
@mcollina Sorry about not closing this up earlier. Thanks again for your work a month or two back!
