### ISSUE TITLE
dynamic reply

### ISSUE THREAD

**Issue by Alexufo** [fastify/fastify-static#112]
Is able to  sendFile work with dynamic content from buffer?
I want to send file without saving on  disk

**Comment by mcollina** [comment]
You can just use reply.send(). Would you like to give us some context?
Il 12 nov 2019, 15:21 +0000, Alexandr <notifications@github.com>, ha scritto:

**Comment by Alexufo** [comment]
Axios don't recognize reply.send('buffer data'). 
But when I request file from  url with static file axios works fine.
axios.get('.../rep.docx', { responseType: 'blob'})

**Comment by Alexufo** [comment]
My fault. It is working example to use axios.post and retrieve buffer from fastify.
https://stackoverflow.com/a/50220596/2497351

Give you my best
