### ISSUE TITLE
Fastify-static http2/https typescript warning

### ISSUE THREAD

**Issue by ZiiMakc** [fastify/fastify-static#114]
When using fastify with https/http2 like this:

```
import fastifyStatic from 'fastify-static'

const https: fastify.FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse> = fastify({
  logger: log,
  ignoreTrailingSlash: true,
  http2: true,
  https: { allowHTTP1: true }
})

https.register(fastifyStatic, { root: path.resolve(__dirname, '../../public'), prefix: '/public/' })
```

You will get typescript warning:
```
error TS2345: Argument of type '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse>, options: { root: string; prefix?: string | undefined; ... 14 more ...; maxAge?: string | ... 1 more ... | undefined; }, callback: (err?: FastifyError | undefined) => void) => void' is not assignable to parameter of type '(instance: FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse>, options: { ...; }, callback: (err?: FastifyError | undefined) 
=> void) => void'.
  Types of parameters 'instance' and 'instance' are incompatible.
    Type 'FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse>' is not assignable to type 'FastifyInstance<Server, IncomingMessage, ServerResponse>'.
      Types of property 'server' are incompatible.
        Type 'Http2SecureServer' is not assignable to type 'Server'.
```

What is the reason of this?

**Comment by mcollina** [comment]
no reason. Making really dynamic code with typescript is hard. PRs are welcome!

**Comment by ReTWi** [comment]
I'm new to typescript, so i will pass it for now to anyone who is more knowledgeable of typescript generics and declaration files, as i don't see a clear way to make it work for different interfaces.

Temporally i changed index.d.ts of fastify-static to:
```
import { Http2SecureServer, Http2ServerRequest, Http2ServerResponse } from "http2"
declare const fastifyStatic: fastify.Plugin<Http2SecureServer, Http2ServerRequest, Http2ServerResponse, {//options }>;
```

**Comment by evanshortiss** [comment]
@ReTWi, do you have a more complete example? What's your `tsconfig`, what other code is in your file?

The following code compiles and runs if I use `npx tsc index.ts --target es6 --module commonjs`:

```ts
import * as fastify from 'fastify'
import { resolve } from 'path'
import { Http2SecureServer, Http2ServerRequest, Http2ServerResponse } from 'http2'

const https: fastify.FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse> = fastify({
    logger: true,
    ignoreTrailingSlash: true,
    http2: true,
    https: { allowHTTP1: true }
})

https.register(require('fastify-static'), {
    root: resolve(__dirname, 'public',),
    prefix: '/public/', // optional: default '/'
})

https.listen(8080)
```

**Comment by ReTWi** [comment]
@evanshortiss i will make a PR in a few minutes to fix this.

My code runs and works too, but there is always a warning from typescript. 
I don't think you need something more to get a warning.

Config is:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "sourceMap": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "removeComments": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictBindCallApply": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "allowJs": true,
    "strictPropertyInitialization": true
  },
  "exclude": [
    "../../node_modules"
  ]
}
```

**Comment by ReTWi** [comment]
@evanshortiss i found that i hae no warning if i use 
`require('fastify-static')`
instead
`import fastifyStatic from 'fastify-static'`

**Comment by evanshortiss** [comment]
@ReTWi you included a compiler error, not warning in the original issue though. Have I misunderstood? A compiler error means the code doesn't compile and therefore does not run.

**Comment by ReTWi** [comment]
@evanshortiss it's error, but it's compiles and work so i sad "warning". Sorry i  misguided you

**Comment by evanshortiss** [comment]
Gotcha, looks like following the plugin structure style from those other packages will help! Nice work on the PR, I see Ethan is reviewing so it'll be all good 👍

**Comment by SahasSaurav** [comment]
![Capture](https://user-images.githubusercontent.com/60291223/173183185-40890e87-8a95-4332-99fd-daac16183738.PNG)

No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ logger: { level: string; transport: { target: string; }; serializers: { res(reply: FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, unknown>): { ...; }; req(request: FastifyRequest<...>): { ...; }; }; }; bodyLimit: number; requestTimeo...' is not assignable to parameter of type 'FastifyServerOptions<Server, FastifyBaseLogger>'.
      Object literal may only specify known properties, and 'http2' does not exist in type 'FastifyServerOptions<Server, FastifyBaseLogger>'.ts(2769)
fastify.d.ts(56, 18): The last overload is declared here.

**Comment by QEDK** [comment]
@ZiiMakc I think the issue still exists:
```
index.ts(6,7): error TS2322: Type 'FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>' is not assignable to type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyBaseLogger, FastifyTypeProviderDefault>'.
  Types of property 'server' are incompatible.
    Type 'Http2SecureServer' is missing the following properties from type 'Server': maxHeadersCount, maxRequestsPerSocket, timeout, headersTimeout, and 4 more.
```

**Comment by mcollina** [comment]
please open a fresh issue with a reproduction
