### ISSUE TITLE
Not working with svelte/sapper middleware

### ISSUE THREAD

**Issue by rdehouss** [fastify/fastify-static#117]
## 🐛 Bug Report

Using fastify-static plugin with sapper middleware gives 404 on any static file

## To Reproduce

Follow these steps: https://www.matthewcantelon.ca/blog/sapper-fastify/
The static files are not served (it gives 404) while it works with sirv

```js
fastify.use(sirv('static'))
```

**Without the sapper middleware, it works**
Would it be an issue with the plugin not doing sth at the end that let the middleware "break"?

## Expected behavior

The static files should be served

## Your Environment

- *node version*: v13.2.0
- "fastify": "^2.10.0"
- "fastify-static": "^2.5.1"
- "sirv": "^0.4.2"
- *os*: Linux
- *any other relevant information*

**Comment by mcollina** [comment]
There is likely some incompatibility between all of these and Fastify connect-middleware compatibility.

Can you please paste a full example (something that can be copy-pasted) or a a link to a github repo that demonstrate the problem? It would help in getting a fix done.

---

What I would recommend is to avoid using the middleware interface and develop a full-blown fastify plugin for sapper.

**Comment by Shyam-Chen** [comment]
Use `middie`.

```js
import Fastify from 'fastify';
import compression from 'compression';
import sirv from 'sirv';
import * as sapper from '@sapper/server';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

async function server() {
  const fastify = Fastify();
  await fastify.register(require('middie'));
  fastify.use(compression({ threshold: 0 }));
  fastify.use(sirv('static', { dev }));
  fastify.use(sapper.middleware());
  return fastify;
}

server()
  .then((fastify) => fastify.listen(PORT))
  .catch((error) => {
    console.error(error);
  });
```
