### ISSUE TITLE
Does this serve static assets from memory?

### ISSUE THREAD

**Issue by ORESoftware** [fastify/fastify-static#119]
## 💬 Questions and Help

Does this serve static assets from memory? If so, that's unclear.

I am looking for an existing solution to this problem:
https://medium.com/@the1mills/node-js-performance-the-most-common-piece-of-missing-middleware-for-servers-in-production-d4aca26b4da2

**Comment by StarpTech** [comment]
The article is only for paid users. fastify-static use https://github.com/pillarjs/send and every file is sent from the filesystem.

**Comment by ORESoftware** [comment]
thanks, I just made the Medium story public, try it now if you want

https://medium.com/@the1mills/node-js-performance-the-most-common-piece-of-missing-middleware-for-servers-in-production-d4aca26b4da2

the goal is to load static assets into memory, and never have to read from disk, for thousands/millions of different clients.

**Comment by StarpTech** [comment]
I'm not completely in the topic but node.js has a memory limit. Your solution can't scale. I think you are trying to solve a nonexistent problem. Static file delivery is already well solved by CDN's or a reverse proxy like Nginx. In practice, clients will download an asset only once and the next request is served from the client cache (browser).

**Comment by ORESoftware** [comment]
1. You have 5 million customers/ browser clients
2. You release a new version of your web front-end
3. All 5 million clients will request a new copy of your static assets.
4. So that is a minimum of 5 million disk reads

it's unlikely that it will pose much problem, since the requests will be staggered out, perhaps over several days. but in any case, the delivery will be faster.

even Apache and NGINX could be sped up in this way, if your static assets are less than 500 MB, it should be fine to load into memory, but ideally they would be less than 100 MB, since 500MB is getting high for memory in Node.js.

**Comment by jsumners** [comment]
1. As @StarpTech said, this sort of thing will eat up the process's memory for a function it isn't even designed for.
2. Use a reverse proxy -- https://github.com/fastify/fastify/blob/5258f421a32592396d9e9999812f6c6096ccf6db/docs/Recommendations.md#use-a-reverse-proxy
3. Use a static assets server behind that proxy that can cache to memory -- https://www.nginx.com/blog/cache-placement-strategies-nginx-plus/

**Comment by StarpTech** [comment]
I don't see how your idea will solve any issue. Let's talk in the context of a regular web app.

- Nginx and other services are optimized for file delivery. This means they already use proper techniques like caching.
- If you release a new version of your web app it doesn't mean that your complete cache is stale. If you use techniques like hashed-URLs only changed files redelivered. Most of the time, files are served by the client's cache.
- If you want to provide high availability and low latency you have to work with CDN's anyway.

**Comment by ORESoftware** [comment]
I agree - Apache and NGINX cache files into memory, and serve from memory. If Node.js is going to serve static assets, it can cache things into memory too. But yes, in general, it's best to set up NGINX or Apache and use them as CDNs etc.

**Comment by Eomm** [comment]
> Right?

Yes, it is, but it is a feature that https://github.com/pillarjs/send should provide.

Closing: duplicate #54 
Eventually, continue the discussion there, thanks
