### ISSUE TITLE
Support preRequest hooks

### ISSUE THREAD

**Issue by amio** [fastify/fastify-static#121]
## 🚀 Feature Proposal

Support `preRequest` hooks, or a middleware like option, for intercepting before handling serving statics.

## Motivation

For cases like, filter files, or serve statics depends on request attributes. In my case, I want to serve `.map` file only to developer instead of all end users.

We could implement this with a hook, or middleware, or something else?

**Comment by Eomm** [comment]
> I want to serve .map file only to developer instead of all end users.

You could add an auth check with [fastify-auth](https://github.com/fastify/fastify-auth#fastify-auth)
so developers can be served by fastify-static, and end users get a 401 error or something else

**Comment by amio** [comment]
Thanks @Eomm, that's nice! While I still wish I could apply this check on static routes only, not every requests, to save some computation resource :D

**Comment by Eomm** [comment]
You can thanks to encapsulation, here a fast snipped where the only request to path registered in the fastify's `instance` variable will be evaluated:

```
fastify.register((instance, opts, next) => {
  instance.register(require('fastify-auth'))
    .after(() => {
      instance.addHook('preHandler', instance.auth([
        fastify.verifyJWTandLevel,
        fastify.verifyUserAndPassword
      ]))
    })

  instance.register(require('fastify-static'), {
    root: path.join(__dirname, 'public'),
    prefix: '/public/' // optional: default '/'
  })
})

fastify.get('/', (req, reply) => {
  reply.send('NO AUTH')
})
```

**Comment by amio** [comment]
Awesome, thanks @Eomm! Exactly what I'm looking for 😘
