### ISSUE TITLE
setNotFoundHandler not triggering hooks

### ISSUE THREAD

**Issue by PierBover** [fastify/fastify-static#126]
## 🐛 Bug Report

The [docs](https://www.fastify.io/docs/latest/Server/#setnotfoundhandler) for `setNotFoundHandler` specify it's possible to use hooks to be triggered before the handler is triggered:

> You can also register a preValidation and preHandler hook for the 404 handler.

When using `fastify-static` these hooks are not being triggered.

## To Reproduce

If you run this code you will see the `preHandler` hook is not being triggered. Disabling the `fastify-static` plugin solves the problem.

```js
const path = require('path');

const fastify = require('fastify')({
	logger: true
});

fastify.register(require('fastify-static'), {
	root: path.join(__dirname, '/static/')
});

fastify.setNotFoundHandler({
	preHandler: (request, reply, next) => {
		console.log('preHandler!');
		next();
	}
}, function (request, reply) {
	reply.status(404);
	reply.send();
});

fastify.listen(5555, '0.0.0.0', function (err, address) {
	if (err) {
		fastify.log.error(err)
		process.exit(1)
	}
	fastify.log.info(`server listening on ${address}`)
});
```

## Expected behavior

When the `setNotFoundHandler` callback is triggered it should also trigger the hooks defined for this handler.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Good spot! The hooks are not triggered when a 404 is called from reply.callNotFound() method.

The best workaround is to use the wildcard option in this module to have precise routes and avoid the wildcard.

**Comment by PierBover** [comment]
Thanks for the solution!

I'm closing this since it's not a plugin issue.
