### ISSUE TITLE
Proposal: dir index

### ISSUE THREAD

**Issue by simone-sanfratello** [fastify/fastify-static#135]
## 🚀 Feature Proposal

I'd like to implement a feature to get the "index" of the directory, if the request is the dir root or "index" or "index.html" - all of that optional and configurable. Output format can be json or html; for html a string for template is required.
Next improvement could optionally add files stats to output

## Motivation

Can be useful to have an index for dir navigation or to quickly expose files

## Example

A draft example could be

### json

```js
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'public'),
  prefix: '/public/',
  index: { // optional
    format: 'json', // optional, default json (?), can be both ?
    names: ['/index', '/index.json', '/'] // optional, default '/'
  }
})
```

request
`GET .../public/images` or `GET .../public/images/index.json`

response
```json
{
  "dirs": ["house", "office"],
  "files": ["bed.jpg", "kitchen.png"]
}
```

### html

```js
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'public'),
  prefix: '/public/',
  index: { 
    format: 'html',
    template: '<html> ... TDB ... </html>',
    names: ['/index', '/index.html', '/'] // optional, default '/'
  }
})
```

request
`GET .../public/images` or `GET .../public/images/index.html`

response
```html
<html>

  DIRS
  <a href="/public/house">house</a>
  <a href="/public/office">office</a>

  FILES
  <a href="/public/bed.jpg" target="_blank">bed.jpg</a>
  <a href="/public/kitchen.jpg" target="_blank">kitchen.jpg</a>
</html>
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to implement this feature? Remember to add unit tests.

**Comment by simone-sanfratello** [comment]
Sure, I just wanted to check if the feature makes sense

**Comment by mcollina** [comment]
I thought about implementing it for a while! :)

**Comment by mcollina** [comment]
Put it behind a flag.

**Comment by simone-sanfratello** [comment]
I made the PR https://github.com/fastify/fastify-static/pull/137

I changed some names from this proposal, the `index` option name was already taken.
I introduced the `lib` dir because I'm not confortable with a single file module, but if this is not consistent, I can put that inside `index.js`.

No need to say, feel free to change anything you like, but please note I get 100% coverage on `lib/dirList.js` and only 2 lines are missing in `index.js` from 100% code coverage.
