### ISSUE TITLE
percent-encoded URLs might fail in glob mode

### ISSUE THREAD

**Issue by shimaore** [fastify/fastify-static#143]
## 🐛 Bug Report

When trying to access a URL containing (for example) `%20` to indicate a space in the filename with `fastify-static` configured with `wildcard: false`:
- if only the file with a space in its name is present, 404 is returned
- if only a file with `%20` in its name is present, 404 is returned
- if both a file containing a space in its name and a file containing `%20` in its name is present, the file containing the space in its name is served.

## To Reproduce

```js
var  fastify = (require('fastify'))({});

fastify.register(require('fastify-static'), {
  root: __dirname,
  prefix: '/',
  wildcard: false
});

fastify.listen().then(console.log);
```

```shell
touch 'a .md'
```

Start JS script, try to get `/a%20.md`: 404

```shell
touch 'a%20.md'
```
Start JS script, try to get `/a%20.md`: OK

```shell
rm 'a .md'
```
Start JS script, try to get `/a%20.md`: 404

## Expected behavior

Since the file containing the space in its name is served properly, it should be available as containing `%20` in its name. This means glob should use percent-encoded URLs for non-unreserved characters (as defined in RFC3986).

## Your Environment

- *node version*: 14
- *fastify version*: 3.4.1
- *os*: Linux

**Comment by shimaore** [comment]
Changing
```
          const route = (prefix + file).replace(/\/\//g, '/')
```
to
```
          const route = (prefix + encodeURI(file)).replace(/\/\//g, '/')
```
in `index.js` seems to do the trick.

**Comment by mcollina** [comment]
Good spot! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
