### ISSUE TITLE
Support passing an array of paths for `root` when registering plugin.

### ISSUE THREAD

**Issue by mmarti** [fastify/fastify-static#144]
## 🚀 Feature Proposal

Support passing an array of paths for `root` when registering plugin.

## Motivation

Applications may have static files in different locations.  Being able to pass an array of locations to check would be extremely useful.  This is currently not possible if you want them to be served off the same prefix.  In other words, you can register `fastify-static` multiple times, each with a different root, but you have to use a unique prefix for each of them, or an error is thrown.  Allowing multiple root paths to be checked would be a cleaner way than registering the plugin multiple times and would allow a single prefix to be used for all of them.

## Example

This is similar to the [Multiple roots](https://www.npmjs.com/package/serve-static) example in the `serve-static` docs:

```js
app.use(serveStatic(path.join(__dirname, 'public-optimized')))
app.use(serveStatic(path.join(__dirname, 'public')))
```

The order of the array would determine the file to serve.  Assume we have the following directory structure:

```
src/
├── apple/
│   ├── a.css
│   └── a.min.css
├── berry/
│   ├── a.css
│   └── b.css
```

We'd register our plugin like so (assume PWD is `src`):

```js
app.register(require('fastify-static'), {
  root: [path.join(__dirname, 'apple'), path.join(__dirname, 'berry')],
  prefix: '/static',
});
```

Examples of access:

```
/static/a.css -> apple/a.css
/static/b.css -> berry/b.css
/static/random.css -> 404
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mmarti** [comment]
Yeah, when I get a bit of free time, I can try getting something working.  Thanks.

**Comment by katywings** [comment]
This feature would be huge :star_struck: :+1:

**Comment by nigelhanlon** [comment]
I think we can close this feature request out now. Support for multiple root directories now works with the latest version.
