### ISSUE TITLE
Missing peer dependency on fastify

### ISSUE THREAD

**Issue by jscheid** [fastify/fastify-static#159]
## 🐛 Bug Report

This package imports `fastify` but doesn't declare a dependency on it (except for a `devDependency`.) This breaks eg. with yarn pnp:

```
../.yarn/cache/fastify-static-npm-3.3.0-0772a5855d-9fda689884.zip/node_modules/fastify-static/index.d.ts:5:60 - error TS2307: Cannot find module 'fastify' or its corresponding type declarations.

5 import { FastifyPlugin, FastifyReply, RawServerBase } from 'fastify'
```

As a workaround, this can be added to `.yarnrc.yml`:

```yml
packageExtensions:
  fastify-static@*:
    peerDependencies:
      fastify: "*"
```

## To Reproduce

Try using this package with a pnp-enabled yarn package.

## Expected behavior

-/-

## Your Environment

- *node version*: 14.14.0
- *fastify version*: 3.7.0
- *os*: Mac
- Yarn version 2.3.3-git.20201103.34883f8

**Comment by mcollina** [comment]
The problem is that npm 6, npm 7, yarn 1 & 2, all have different behavior and expectations from peerDependencies. My best recommandation is to simply avoid them everywhere.

Note that this is only a TS/transpiling issue because everythings works fine at runtime.

**Comment by mcollina** [comment]
wdyt @fastify/typescript?

**Comment by Ethan-Arrowood** [comment]
I have little understanding of yarn pnp 😕 that yarnrc thing looks like a good thing to document at the least. Sorta like a "Use Fastify with Yarn PNP".

**Comment by merceyz** [comment]
Even though it's just for the types it should be declared either way, randomly getting `any` types because a dependency wasn't placed in the right location is not fun.
