### ISSUE TITLE
New files not serving

### ISSUE THREAD

**Issue by flleeppyy** [fastify/fastify-static#161]
## 🐛 Bug Report

Adding new files to a folder then trying to access those files through fastify does not work and thinks the file does not exist, even though it does, and I have to restart the node instance completely in order for it to work

## To Reproduce

```js
app.register(fastifyStatic, {
  root: path.join(__dirname, "public"),
  wildcard: "/**",
})
```

## Expected behavior

When placing a new file in the public directory, I should be able to go to it on my website without having to restart the node instance

## Your Environment

- *node version*: 14.9.0
- *fastify version*: >=3.5.0
- *os*: Ubuntu 20.04.1

**Comment by mcollina** [comment]
the value for `wildcard` is either `true`, `false` or `undefined`. There is a bug that leads to a string being interpreted as `false`. This results in fastify-static not adding the wildcard route, which has documented will index all the files on disk at startup.

The fix in your code is to remove the `wildcard` option.
The fix in fastify-static is to throw if it's not a boolean.

**Comment by jsumners** [comment]
> The fix in fastify-static is to throw if it's not a boolean.

Or just stick https://www.npmjs.com/package/boolean on it.

**Comment by Sebring** [comment]
Should it really throw on string as a non zero string is _truthy_ and empty is _falsy_, hence `'/**' == true`?

**Comment by mcollina** [comment]
that's also ok

**Comment by Sebring** [comment]
Browsed the code and wildcard is a _glob_ from what I understand, not a boolean, heh.

**Comment by climba03003** [comment]
When `wildcard` is `undefined` or `true`, it will dynamic scan the folder and return the file you need, so new file will be added.
https://github.com/fastify/fastify-static/blob/c7cfa9f5812885316af0527bac3e008b9a6d4040/index.js#L164-L167

However, when `wildcard` is  `string`, it will scan the directory by glob in launch. No, `asterisk` route will be added.
So, no new files will be served.
https://github.com/fastify/fastify-static/blob/c7cfa9f5812885316af0527bac3e008b9a6d4040/index.js#L176-L193

I think it should be the intended behavior.

**Comment by mcollina** [comment]
> I think it should be the intended behavior.

So is there something to fix?

**Comment by climba03003** [comment]
`glob` handler is added in #83 to prevent adding `asterisk` route. If the fix is needed, it will be something reverting #83.

**Comment by mcollina** [comment]
`wildcard` is not expected to be a string, and we should throw if it's a string. That's the fix I mentioned at the top.. why is this not feasible?

**Comment by climba03003** [comment]
you can expect it to be boolean only, but how can to tackle with the case for #64?
we need the a way to not adding a wildcard route and update the route when file change.
So, I give the third answer (add a file watcher)  to this question.

**Comment by mcollina** [comment]
Adding a watcher won't work as you can't define routes after the process is started.

**Comment by climba03003** [comment]
Then, I will go for `document` this behavior as it is working properly.

`wildcard` option mean adding a `wlidcard` route or not. `false` or `string` option will prepend the `file` route when launch, it will not serve the file added after fastify `ready`. The reason behind is that if you do not add a `wildcard` route, it is no way for `fastify-static` to know whether the new file is not exist beforehand and have a route to handle.

Passing `wildcard` as `string` is more like an feature in my eyes and this is documented.
> If set to false, fastify-static globs the filesystem for all defined files in the served folder (${root}/**/*), and just creates the routes needed for those. If set to a glob string pattern, fastify-static will use the provided string when globing the filesystem (${root}/${wildcard}).
> 
> The default options of https://www.npmjs.com/package/glob are applied for getting the file list.

**Comment by mcollina** [comment]
I think it's better to remove that functionality, yes. I didn't even recall it was documented (my bad) :/.
