### ISSUE TITLE
list option not working

### ISSUE THREAD

**Issue by gidmoth** [fastify/fastify-static#164]
## 🐛 Bug Report

When I enable the list option like so:

```
fastify.register(require('fastify-static'), {
    root: path.join(__dirname, 'public'),
    prefix: '/public/',
    list: true
  })
```
It doesn't work. GET requests to `.../public` give:

`{"message":"Route GET:/public not found","error":"Not Found","statusCode":404}`

## To Reproduce

```js
const path = require('path')
const fastify = require('fastify')({
    logger: true
  })

  fastify.register(require('fastify-static'), {
    root: path.join(__dirname, 'public'),
    prefix: '/public/',
    list: true
  })

  fastify.listen(3000, function (err, address) {
    if (err) {
      fastify.log.error(err)
      process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
  })
```

Also create `public` and place a file there:

```
mkdir ./public
cat >> public/hello.txt
hello!
^D
```

Then run the server and try:

```
curl http://localhost:3000/public
```

or (same result):

```
curl http://localhost:3000/public/
```

## Expected behavior

I expect to get a list like the one described in the documentation for a request like `GET .../public`:

`{ "dirs": [], "files": ["hello.txt"] }`

## Your Environment

- *node version*: 14.14.0
- *fastify version*: 3.9.2
- *os*: Linux
- *fastify-static version*: 3.3.0

**Comment by Eomm** [comment]
The `root` folder doesn't expose the file list by default.

YOu need to set:

```
fastify.register(require('./index'), {
  root: path.join(__dirname, '/public'),
  prefix: '/public',
  index: false,
  list: true
})
```

**Comment by gidmoth** [comment]
Ok, thx. How should the index to require look like? I guess a function returning the index as object, right?
And the "index" to require should pass the list option to fastify-static, right? But I can't make any sense of the "index" option, perhaps you could clarify with a full working example.

**Comment by mcollina** [comment]
@gidmoth would you mind to send a PR to update the README?

**Comment by gidmoth** [comment]
I would be happy, as soon as I understand it. But I can't provide a working example on the base of Eomms Answer, sry.

**Comment by gidmoth** [comment]
I can do the following to archive what I wanted to archive with `fastify-static`s `list` option. But note that it neither uses the option nor is it exactly what @Eomm suggests.

Take this code as my server:

```
const path = require('path')
const fastify = require('fastify')({
    logger: true
  })
const fs = require('fs')

const idx = (mypath) => {
  let list = {dirs: [], files: []}
  items = fs.readdirSync(mypath, { withFileTypes: true })
  console.log(items)
  items.forEach(item => {
    item.isFile() && list.files.push(item.name)
    item.isDirectory() && list.dirs.push(item.name)
  });
  return list
}

fastify.register((fastify, options, done) => {
  fastify.decorate('index', idx)
  fastify.register(require('fastify-static'), {
    root: path.join(__dirname, 'public'),
    prefix: '/public'
  })
  fastify.get('/public', (req, reply) => {
    reply.send(fastify.index(path.join(__dirname, 'public')))
  })
  fastify.get('/public/', (req, reply) => {
    reply.send(fastify.index(path.join(__dirname, 'public')))
  })
  done()
})

fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

Also note that there seems to be some interference of `fastify-static` with the default behavior of `fastify.get`. That is, setting `prefixTrailingSlash: 'both'`. So I have to declare both routes, `/public` and `/public/`.

Then make the directory and some content for testing:

```
mkdir -p ./public/test
cat > public/hello.txt
hello!
^D
```

This gives the results:

```
curl http://localhost:3000/public/hello.txt
hello!
curl http://localhost:3000/public/
{"dirs":["test"],"files":["hello.txt"]}
curl http://localhost:3000/public
{"dirs":["test"],"files":["hello.txt"]}
```

I can live with that solution, but I still think the `list` option would be more convenient. @mcollina this obviously doesn't fit for a README suggestion on the `list` option, but perhaps it helps someone struggling with a similar problem.

**Comment by mcollina** [comment]
This likely need a PR to fix this behavior, it should work out of the box.

**Comment by jwbargsten** [comment]
@gidmoth I ran into this today and after looking a bit at the code, it seems that the `list` and `index` options need to be set as follows if you want your desired behaviour:

```js
fastify.register(require("fastify-static"), {
  root: path.join(__dirname, "node_modules"),
  prefix: "/foo",
  list: true,
  index: false,
})
```
What happens when `index` is **not** set to `false`? If you check [the docs of the send module](https://www.npmjs.com/package/send#index), you see that fastify-static is trying to load `index.html` in that directory. This file does not exist, so naturally you'll get a 404.

Once you set the options as suggested above, you can already run e.g. curl: `curl -L http://localhost:3000/foo/`. Probably you want to also use the url without `/` at the end, so you need to add the option `redirect: true`, too. This leaves you with

```js
fastify.register(require("fastify-static"), {
  root: path.join(__dirname, "node_modules"),
  prefix: "/foo",
  redirect: true,
  list: true,
  index: false,
})
```

and `curl -L http://localhost:3000/foo` will also work.

At least this setup worked for me. Hope it helps!

**Comment by gidmoth** [comment]
OK, thx @jwbargsten , works for me too. The `index` option for the send-module was the point. I'll do a pull-request to the README asp.
