### ISSUE TITLE
reply.sendFile to support absolute path

### ISSUE THREAD

**Issue by lanyusan** [fastify/fastify-static#177]
## 🚀 Feature Proposal

Currently `reply.sendFile` either resolve with preset root or use a second parameter as root. 

I suggest that `reply.sendFile` support a single parameter with absolute path or could check if second parameter is empty string, i.e ` '' `to still do join.

## Motivation

I have a case where handler needs to resolve the url to a file and return an aboslute path.
Now if I call `reply.sendFile(filepath, '')`, it is still resolved to something like `path.join(root, filepath)`

## Example

reply.sendFile('/home/www/abc/index.html')

**Comment by mcollina** [comment]
This is by design to protect users from attackers interested in specific files on the filesystem.

**Comment by lanyusan** [comment]
But it is a backend api. Shouldn't it be the api caller's responsibility to do security check? 
But anyway, it is NOT a critical problem. I can live with it. Thanks.

**Comment by mcollina** [comment]
Unfortunately doing that check safely is hard and risky to do: most developers would leave a path open for attackers.
