### ISSUE TITLE
Adding .head routes

### ISSUE THREAD

**Issue by jeffrson** [fastify/fastify-static#184]
## 🚀 Feature Proposal

fastify-static could be enhanced by supplying
fastify.head
routes additionally to existing .get.

## Motivation

HTTP HEAD request is a simple way to receive information about length of file, date of modification and etag. see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

As it currently stands, every HTTP HEAD request (curl -I) gives 404 error.
The rather new fastify option exposeHeadRoutes does never return when used with fastify-static.

## Example

For files it could be tested whether they need to be downloaded because of updates. Also it might be checked whether there is enough space in local cache.

**Comment by mcollina** [comment]
Would you like to send a PR to add this feature?

**Comment by jeffrson** [comment]
Unfortunately I don't know fastify well enough.

I tried to find out why fastify-static through fastify with `{ exposeHeadRoutes: true }` never returns when HEAD method is called. But I failed within a reasonable time budget. Though I could pinpoint some problems I have no idea how to fix.

It's a pity, I would've liked to do it
