### ISSUE TITLE
Symbolic-Link doesn't work without wildcard

### ISSUE THREAD

**Issue by prab-it** [fastify/fastify-static#185]
## 🐛 Bug Report

Symbolic link doesn't work if I set `wildcard: false`.

## To Reproduce

1 - add a `symbolic-link` in your `public` directory: `cd public && ln -s ../assets assets`
2 - set `wildcard: false`

```js
await server.register(fastifyStatic, { root: [path.join(__dirname, 'public')], wildcard: false });
```

## Expected behavior

`fastify-static` should `serve` the content inside the `symbolic-link` if `wildcard: false`.

## Your Environment

- *node version*: 14.15.1
- *fastify version*: >=3.14.0
- *os*: Mac

**Comment by mcollina** [comment]
I don't know why it's not working, would you like to investigate and send a fix?

**Comment by prab-it** [comment]
ok, no problem

**Comment by prab-it** [comment]
@mcollina sorry, I think the issue was on my side... 🤔 I don't know what was the issue, but now it works fine!
If I hit the issue, I investigate furthermore this time! Really sorry, probably it was my mistake.

**Comment by mcollina** [comment]
No worries!

**Comment by prab-it** [comment]
BTW, thanks for `Fastify`! :)

**Comment by prab-it** [comment]
@mcollina the issue is related to `sub-directories` in `symbolic-link` and I think we can fix this issue like this:

`fastify-static/index.js:196`
```diff
- const globPattern = '**/*'
+ const globPattern = '**/**'
```

**Comment by mcollina** [comment]
Sure thing, send a PR with a unit test!
