### ISSUE TITLE
http url in prefix not working

### ISSUE THREAD

**Issue by srigar** [fastify/fastify-static#196]
## 🐛 Bug Report

Server not getting started, if we give complete http url in `prefix` property. It is considering prefix url as route.

## To Reproduce

1. Add complete http url in prefix

```js
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'public'),
  prefix: 'http://localhost:3003/',
})
```
<img width="758" alt="Screenshot 2021-05-04 at 11 25 41 AM" src="https://user-images.githubusercontent.com/20384652/116965456-7b2fc980-accb-11eb-8a79-367551dea45d.png">

## Expected behavior

Without any issue server should start.

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Mac, Linux

**Comment by mcollina** [comment]
Thanks for reporting. We do not support using an URL as a prefix. Is this documented somewhere?

**Comment by srigar** [comment]
@mcollina no it is not documented, but we are using webpack asset manifest to write assets in json file. For that I need to pass complete URL in assetPath. Is there any option/workaround for that?

**Comment by mcollina** [comment]
It's really not clear what you are trying to achieve. If the files are served by another process, you might consider using `fastify-http-proxy` as a proxy.

**Comment by srigar** [comment]
Basically we have our own internal framework in react for micro application, for that we need to pass assetPath as complete url.
