### ISSUE TITLE
`list` option cause fastify to crash if `root` is an array

### ISSUE THREAD

**Issue by max-hk** [fastify/fastify-static#203]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

v16.1.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3.1

### Description

If you pass an array of string to `root`, but also enabled the `list` option, fastify will crash.

### Cause

`path` function expect `root` argument to be a string, but fastify-static accepts string array in the `root` option.

https://github.com/fastify/fastify-static/blob/761dfe579bd53a79341db81bc69a9096868e40ab/lib/dirList.js#L96-L106

https://github.com/fastify/fastify-static/blob/761dfe579bd53a79341db81bc69a9096868e40ab/index.js#L125

### Steps to Reproduce

```js
fastify.register(fastifyStatic, {
  root: [path.resolve("static"), path.resolve("dist")],
  prefix: "/public",
  list: {
    format: "json",
    names: ["index", "index.json", "/"],
  },
});
```

Then go to `http://127.0.0.1:3000/public/`.

Fastify will throw an error and exit.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1176:7)
    at Object.path (/path/to/project/node_modules/fastify-static/lib/dirList.js:105:30)
    at SendStream.<anonymous> (/path/to/project/node_modules/fastify-static/index.js:121:55)
    at SendStream.emit (node:events:365:28)
    at SendStream.error (/path/to/project/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/path/to/project/node_modules/send/index.js:421:12)
    at next (/path/to/project/node_modules/send/index.js:763:28)
    at /path/to/project/node_modules/send/index.js:771:23 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Expected Behavior

We should either...

- Document that `list` option only works when `root` is a string, enforce the rule in TypeScript typings and throw error at the time when an invalid config is passed to fastify-static, or

- Let fastify-static "reply" the combination of all files and directories within the folders defined in `root`.

**Comment by maxloh** [comment]
@mcollina @delvedor @Eomm Can you take a look at this?

**Comment by mcollina** [comment]
Looks like a bug! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
As you wish!

**Comment by maxloh** [comment]
Ok. 

But I am busy this weekend. Give me some time for that.

**Comment by maxloh** [comment]
Blocking: #208.
