### ISSUE TITLE
Filtering out requests coming from fasitfy-static?

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-static#212]
If you use some kind of hooks, either `onRequest` or `preHandler`, for for example user information, account stuff, static files requests are decorated as well. Sometimes that's not required/needed. Is there some kind of way to check which `plugin` or `module` served/processed that request/response to filter them out?

**Comment by mcollina** [comment]
You can easily do that:

```js
app.register(async function (app) {
  app.addHook('onRequest', ...)

  app.get('/hello/', () => 'world')
})

app.register(async function (app) {
  app.register(require('fastify-static'), { ... })
})
```

**Comment by yaneony** [comment]
So, the only possible way is to register 'fastify-static' after all the routes, right? There is no flag bein set, either on request or response which identify static files, like just 'isStatic: true' ?!
