### ISSUE TITLE
Typescript: ListOption for `format: 'json'` is invalid

### ISSUE THREAD

**Issue by lordnox** [fastify/fastify-static#222]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.1

### Plugin version

4.2.2

### Node.js version

14.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4 (Apple M1 Chip)

### Description

The type for list (`boolean | ListOptions`) is not correct for the `json` case:

```typescript
interface ListOptions {
  format: 'json' | 'html';
  names: string[];
  render: ListRender;
}
```

It should not include the `render` property as it is not used in `json` but required here

### Steps to Reproduce

```typescript
  const staticOptions: FastifyStaticOptions = {
    root: path.resolve(options.imagePath),
    prefix: options.path,
    dotfiles: 'ignore',
    prefixAvoidTrailingSlash: true,
    list: {
      format: 'json',
      names: ['index', 'index.json', '/', ''],
     // missing render 
    },
  }
```

### Expected Behavior

```typescript
type ListOptions {
  format: 'json';
  names: string[];
} | {
  format: 'html';
  names: string[];
  render: ListRender;
}
```

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by is2ei** [comment]
This issue is still a problem.
e.g. https://stackblitz.com/edit/node-yonvhw?file=index.ts
