### ISSUE TITLE
premature close at onclosenexttick when running on AWS Fargate

### ISSUE THREAD

**Issue by igorshmukler** [fastify/fastify-static#231]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

4.2.3

### Node.js version

12.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

ubuntu-latest

### Description

I am using fastify and fastify-static as an SSR server. Locally, it works fine. Under AWS Fargate code running inside my container errs, fairly often. The easiest way to trigger the problem is by running Google PageSpeed test.

A sample error is below:

```
{
    "level": 50,
    "time": 1630436845304,
    "pid": 1,
    "hostname": "07f3ccb2c7a84af983e545c1b1a2924c-45249757",
    "reqId": "req-8e",
    "stack": "Error: premature close\n    at onclosenexttick (/ssr/node_modules/end-of-stream/index.js:54:86)\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)",
    "type": "Error",
    "msg": "premature close"
}
```

I know that the `fastify-static` plugin had an issue with this, and it seems that people believe that the issue has been resolved. It has not been, or perhaps something got broken again.

### Steps to Reproduce

```
'use strict';

import { preloadAll } from '@react-loadable/revised';

const fastify = require('fastify');
const shutdown = require('fastify-graceful-shutdown');
const compress = require('fastify-compress');
const fp = require('fastify-plugin');
const path = require('path');
const loader = require('./loader');

const main = async () => {
  process.on('unhandledRejection', err => {
    console.error(err);
    process.exit(1);
  });

  const server = fastify({ logger: true });
  server.register(shutdown);

  server.register(compress);
  server.register(require('fastify-static'), {
    root: path.join(__dirname, '../build/static'),
    prefix: '/static',
    decorateReply: false
  });
  server.register(require('fastify-static'), {
    root: path.join(__dirname, '../build/icons'),
    prefix: '/icons',
    decorateReply: false
  });
  server.get('/*', fp(loader));
  server.head('/*', fp(loader));

  const PORT = process.env.PORT || 3000;
  const address = await server.listen(PORT, '0.0.0.0');
  server.log.info(`Server running at: ${address}`);

  server.gracefulShutdown((signal, next) => {
    next();
  });
  module.exports = server;
};

preloadAll().then(() => {
  main();
});
```

### Expected Behavior

I expect to not see errors in the log. I also expect Lighthouse [Google PageSpeed] test to work with my fastify SSR server, as it works with express.

**Comment by mcollina** [comment]
Can you please upload a full example? There are quite a few things missing here to see what would be the problem, e.g. the `./loader.js` file.

> I know that the fastify-static plugin had an issue with this, and it seems that people believe that the issue has been resolved. It has not been, or perhaps something got broken again.

Could you please create a script that we can use to reproduce this locally?

**Comment by igorshmukler** [comment]
> Can you please upload a full example? There are quite a few things missing here to see what would be the problem, e.g. the `./loader.js` file.
> 
> > I know that the fastify-static plugin had an issue with this, and it seems that people believe that the issue has been resolved. It has not been, or perhaps something got broken again.
> 
> Could you please create a script that we can use to reproduce this locally?

The code is not open source, per se. I am happy to share the setup privately. Could someone please email me at ${firstName}.${lastName}@gmail and I will email back the 3-4 files needed.

Just a note for clarity - locally eg when I execute the code on my laptop running macOS directly, it is working just fine. I am having consistent issues all the time while running under AWS Fargate. I did not try to simulate the same workload against a local docker setup. Hence, I am not certain whether a single docker container would have the same problem.

**Comment by jsumners** [comment]
> The code is not open source, per se. I am happy to share the setup privately. Could someone please email me at ${firstName}.${lastName}@gmail and I will email back the 3-4 files needed.

No one asked you to post private code. You were asked to post a full reproduction of the issue.

**Comment by igorshmukler** [comment]
> > The code is not open source, per se. I am happy to share the setup privately. Could someone please email me at ${firstName}.${lastName}@gmail and I will email back the 3-4 files needed.
> 
> No one asked you to post private code. You were asked to post a full reproduction of the issue.

@jsumners thank you for trying to help. unfortunately, I am not exactly sure what you were trying to do. did you assume that because Matteo and yours truly have foreign-sounding names, we could your help translation help and without it, mine and/or Matteo's command of English would be insufficient? the truth is, I understood Matteo well and he probably understood me. thank you again, but at this time your assistance is not needed.

**Comment by kibertoad** [comment]
@igorshmukler Being passive-aggressive is not a great way to get help from open source maintainers. Noone here is paid for doing what they are doing. Chances of someone spending their time to reach out via email are close to zero. Burden is on you to spend time to prepare full reproduction, appropriate for sharing on a public repo, if you want to be helped.

**Comment by igorshmukler** [comment]
> @igorshmukler Being passive aggressive is not a great way to get help from open source maintainers. Noone here is paid for doing what they are doing. Chances of someone spending their time to reach out via email are close to zero. Burden is on you to spend time to prepare full reproduction, appropriate for sharing on a public repo, if you want to be helped.

@kibertoad  i closed the issue. It is too bad that you find time to vent your frustrations instead of doing something useful. maybe feel free to plunk me, so anything posted by me is never seen by you. i will be able to live with that.
