### ISSUE TITLE
Add options overload parameter to sendFile function

### ISSUE THREAD

**Issue by mav-rik** [fastify/fastify-static#238]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Sometimes it's required to control cache headers more granularly, so it would be nice to have an option to overwrite the options while calling `sendFile` (just like it's already done for `download`).

### Example

```js
fastify.get('/path', function (req, reply) {
  return reply.sendFile('some-file.js', { maxAge: 0 })
})

fastify.get('/path/custom', function (req, reply) {
  return reply.sendFile('some-file.js', 'custom-filename.js', { maxAge: 0 })
})
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mav-rik** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

done, new pull request #239
