### ISSUE TITLE
files like a%20.md are never reachable

### ISSUE THREAD

**Issue by mav-rik** [fastify/fastify-static#240]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3

### Plugin version

4.2.3

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

#143 isn't actually fixed.

files with `%` char will have problems

### Steps to Reproduce

```
touch 'a .md'
touch 'a%20.md'
```

serve files

try to request `/a%2520.md` and you'll get `a .md`

### Expected Behavior

it should be possible to fetch `a%20.md` file using url `/a%2520.md`

The problem is in `send` function:
```js
const stream = send(request.raw, pathnameForSend, options)
```
According to [docs](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f7be993317280927a66edf992efe6828ef18cc1/types/send/index.d.ts#L15) path should be encoded URL:
```js
/**
 * Create a new SendStream for the given path to send to a res.
 * The req is the Node.js HTTP request and the path is a urlencoded path to send (urlencoded, not the actual file-system path).
 */
```

So when we request `/a%2520.md` it gets decoded to `/a%20.mb` and then fed to `send`. Again `send` does decode the path and we get `a .md` file.

Solution is to put `encodeURI` here:
```js
const stream = send(request.raw, encodeURI(pathnameForSend), options)
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mav-rik** [comment]
@mcollina I found that the problem is deeper. First this [issue](https://github.com/fastify/fastify/issues/3356) must be solved.
