### ISSUE TITLE
Fastify Static bug

### ISSUE THREAD

**Issue by ACenterA** [fastify/fastify-static#263]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.X

### Plugin version

1.x.x

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

It uses ts-node

Error

```
{"level":50,"time":1641573386907,"pid":3474148,"hostname":"acentera-xps9560","reqId":"req-1","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /home/flavalliere/dev/data/workspaces/acentera/fastify-static-bug/node_modules/fastify/lib/wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
```

It depends on various configuration, i tried an empty project and could not reproduce, but in this one I could 

### Steps to Reproduce

git clone https://github.com/ACenterA/fastify-static-bug

cd fastify-static-bug
npm i
npm run dev

curl -vv 'http://127.0.0.1:8080/static/afsdfs'
curl -vv 'http://127.0.0.1:8080/static/a.js'

### Expected Behavior

Should not hang when file not existsf

**Comment by mcollina** [comment]
There seems to be some conflicts between the various options - I never tried this specific configuration. Would you like to send a PR to fix this?

**Comment by zbo14** [comment]
@ACenterA [this](https://github.com/ACenterA/fastify-static-bug/blob/main/server.ts#L146) route conflicts with the Not Found handler. If you comment out the route or change the path so it doesn't conflict with the static root, then you should see the correct behavior.

**Comment by ACenterA** [comment]
Hello @zbo14  i see it make sense, I guess we do not need the notfound handler then since all of our process is actually in the 

fastify.get('*'....  handler)

It is simply weird that it works with an 'single' root  vs an list....

If [https://github.com/ACenterA/fastify-static-bug/blob/main/server.ts#L83](this) is   not an array it works without issues....

**Comment by ACenterA** [comment]
I guess we could close this issue then.
