### ISSUE TITLE
Allow to override fs

### ISSUE THREAD

**Issue by gajus** [fastify/fastify-static#269]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I am writing a middleware for webpack similar to https://www.npmjs.com/package/webpack-dev-server.

The latter is storing files in memory, therefore in order for it to work with `fastify-static`, I would need to have a way to override the `fs` instance that `fastify-static` is using to find / read file.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gajus** [comment]
Turns out this doesn't solve my problem.

I needed to implement my own method for reading files from `memfs` and serving them.

**Comment by mcollina** [comment]
Feel free to open an issue in the fastify org to discuss the design.
