### ISSUE TITLE
404 -> unable to serve index.html -> Trying to send a NotFound error inside a 404 handler. Sending basic 404 response.

### ISSUE THREAD

**Issue by fraprion** [fastify/fastify-static#295]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

4.6.1

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I want to return the index.html as default, when the route is not found.
This is necessary because otherwise this will mess up my angular routing.

`    Fastify.register(FastifyStatic, {
        root: "process.env.PUBLIC_DIR",
    })`
`Fastify.setNotFoundHandler(function (request, reply) { reply.sendFile('${process.env.PUBLIC_DIR}/index.html') })`

_Trying to send a NotFound error inside a 404 handler. Sending basic 404 response._

Maybe I miss something crucial but setNotFoundHandler seems to be the correct approach.

Same issue in v5.0.2.

### Steps to Reproduce

1. localhost:55555 -> serves index.html
2. angular changes the url to localhost:55555/home
3. F5 -> localhost:55555/home is not found -> 404

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by fraprion** [comment]
https://github.com/fraprion/not-found-index

Hope this helps.

**Comment by fraprion** [comment]
`reply.sendFile("index.html")`
I always tried to send the file with absolute path.

Now the message actually makes sense:
Trying to send a '_File_ NotFound error' inside a 404 handler. Sending basic 404 response.
Maybe you could improve this message:
File not found. Cannot send a NotFound error as response from inside a 404 handler. Sending basic 404 response.


Thank you!
Keep up the good work.
