### ISSUE TITLE
Static files not served with "wildcard: false" on windows

### ISSUE THREAD

**Issue by ZiiMakc** [fastify/fastify-static#299]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

3.0.1

### Node.js version

16.15.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I would like to disable `wildcard` to serve some files like `favicon.ico` for root requests `GET /favicon.ico` explicitly without glob.

Issue is that when `wildcard: false` files not served, while with `wildcard: true` they do.

```
import fastifyStatic from "@fastify/static";
import fp from "fastify-plugin";
import fastify from "fastify";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

function getDir(importMeta) {
  return dirname(fileURLToPath(importMeta.url));
}

const dir = getDir(import.meta);

const appFiles = async (app) => {
  await app.register(fastifyStatic, {
    root: join(dir, "./assets"),
    wildcard: false,
    decorateReply: true,
    list: true,
    prefix: "/",
    index: false,
  });
};

const appFilesPlugin = fp(appFiles, {
  name: "app-files",
});

const app = fastify({ logger: true, disableRequestLogging: false });
await app.register(appFilesPlugin);

app.get("/", {
  async handler() {
    return { ok: true };
  },
});

app
  .listen(3000, "0.0.0.0")
  .then(() => console.error("listening"))
  .catch((err) => console.error(err));
```

### Steps to Reproduce

https://github.com/ZiiMakc/test

### Expected Behavior

 `GET /favicon.ico` should serve a file.

**Comment by ZiiMakc** [comment]
In library itself I can see that `const files = await globPromise(path.join(rootPath, globPattern), { nodir: true })` is resolved to empty array, while path is correct.

**Comment by ZiiMakc** [comment]
Oh, I see that it was fixed by [PR](https://github.com/fastify/fastify-static/pull/297)

**Comment by ZiiMakc** [comment]
Can we please release a new version to apply fix?

**Comment by mcollina** [comment]
v6.1.0 is released with the above change. If you'd like to issue a PR to fix it also on v5 (branch `v5.x`), that would be great. Cherry-picking this [commit](654c7f578583460d02c26f0eed0cb3b9ff7f02a0) might be enough.
