### ISSUE TITLE
URL parameter "format=html" causes an error "options.render is not a function"

### ISSUE THREAD

**Issue by is2ei** [fastify/fastify-static#307]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

5.0.2

### Node.js version

16.14.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04.0

### Description

The option `list.format=html` requires `list.render`.

https://github.com/fastify/fastify-static#listformat
> Directory list can be also in html format; in that case, list.render function is required.

The problem is that it is possible to pass `list.format=html` using the URL parameter even though `list.render` option is not given. 

### Steps to Reproduce

1. Register `@fastify/static` with `list: true`.
2. Access the URL with query parameter `?format=html`.
3. You will see an error.

short example:
```javascript
const fastify = require('fastify')();
const path = require('path');

fastify.register(require('@fastify/static'), {
  root: path.join(__dirname, 'public'),
  index: false,
  list: true,
});

fastify.listen(3000);
```

error example:

```
{"statusCode":500,"error":"Internal Server Error","message":"options.render is not a function"}
```

I created an example on stackblitz: https://stackblitz.com/edit/node-hdvl2e?file=index.js

<img width="1398" alt="Screen Shot 2022-05-21 at 20 29 16" src="https://user-images.githubusercontent.com/3948353/169649687-afd84c4b-a15d-4ab3-a31f-fb07afaebfe5.png">

### Expected Behavior

I guess we have some options.
- Allowing `list.render` with `list.format=json`.
- Disabling `?format=html` in URL parameter.
- Documenting not to use `?format=html`.

**Comment by mcollina** [comment]
I think the first option is the way to go.
