### ISSUE TITLE
Add `disableRequestLogging` as override in types file to prevent request logs

### ISSUE THREAD

**Issue by mage1k99** [fastify/fastify-static#309]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

5.0.0

### Node.js version

16.13.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

5.17.5-arch1-1

### Description

Disable logging for a specific route, fastify provides with the option `disableRequestLogging`. when it comes to fastify static with typescript its not possible as it throws an error saying
```log
No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyStaticOptions, Server>, opts?: FastifyRegisterOptions<FastifyStaticOptions> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ root: string; prefix: string; decorateReply: false; dotfiles: "ignore"; etag: false; disableRequestLogging: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyStaticOptions> | undefined'.
      Object literal may only specify known properties, and 'disableRequestLogging' does not exist in type 'FastifyRegisterOptions<FastifyStaticOptions>'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyStaticOptions, Server>, opts?: FastifyRegisterOptions<FastifyStaticOptions> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifyPluginCallback<FastifyStaticOptions, Server>' is not assignable to parameter of type 'FastifyPluginAsync<FastifyStaticOptions, Server>'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifyStaticOptions, Server> | FastifyPluginAsync<FastifyStaticOptions, Server> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type '{ root: string; prefix: string; decorateReply: false; dotfiles: "ignore"; etag: false; disableRequestLogging: boolean; }' is not assignable to parameter of type 'FastifyRegisterOptions<FastifyStaticOptions> | undefined'.
      Object literal may only specify known properties, and 'disableRequestLogging' does not exist in type 'FastifyRegisterOptions<FastifyStaticOptions>
```

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/46259860/169700314-8344d119-220f-4dd7-9d4e-8ad2f604eb3c.png)

So If open the types file (`index.d.ts`) and add `disableRequestLogging` to `FastifyStaticOptions` interface. it allows and works good as expected

### Expected Behavior

Does not show error while compiling the typescript file and allow to use `disableRequestLogging` as options to fastifyStatic while registering it

**Comment by mage1k99** [comment]
![image](https://user-images.githubusercontent.com/46259860/169700467-c4529f89-c008-467c-9b13-b4b4d76d6403.png)

**Comment by mage1k99** [comment]
I know, I could add `//@ts-ignore` but it would be better if its added

**Comment by mcollina** [comment]
Where is `disableRequestLogging` defined? As far as I know this is an option of the main `fastify` factory: https://www.fastify.io/docs/latest/Reference/Server/#disablerequestlogging.

cc @fastify/typescript can you take a look?

**Comment by mage1k99** [comment]
> Where is `disableRequestLogging` defined? As far as I know this is an option of the main `fastify` factory: https://www.fastify.io/docs/latest/Reference/Server/#disablerequestlogging.
> 
> cc @fastify/typescript can you take a look?

I'm new to typescript, the type declaration of `disableRequestLogging` option of fastify is defined in [Line 622, instance.d.ts](https://github.com/fastify/fastify/blob/2ac0a666a8ef8eb4b8b79b38935265864238995f/types/instance.d.ts#L622)

Adding `disableRequestLogging` as boolean type to [FastifyStaticOptions](https://github.com/fastify/fastify-static/blob/c758497bd90137714f76ae2fc8c1e171dcde6f00/index.d.ts#L73) interface will solve this issue, I guess

**Comment by mage1k99** [comment]
I have added a pr #310

**Comment by mage1k99** [comment]
I have misunderstood from this comment https://github.com/fastify/fastify/issues/3036#issuecomment-825592472

**Comment by mage1k99** [comment]
Finally Figured out the issue, I need to disable fastify's default logger. sorry for the issues caused by me. I'm closing this issue
