### ISSUE TITLE
Add request object to allowedPath option

### ISSUE THREAD

**Issue by gurumaxi** [fastify/fastify-static#319]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Is it possible to add the request object as a third parameter to allowedPath the option?
`(pathname, root, request) => true`

### Motivation

By doing so, a more complex path authentication is possible.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
