### ISSUE TITLE
Fastify fastify-static deprication still showing even after updated to @fastify/static@5.0.0.

### ISSUE THREAD

**Issue by eevan7a9** [fastify/fastify-static#326]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.20.2

### Plugin version

5.0.0

### Node.js version

16.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 18.04.6 LTS

### Description

👋Hello everyone

I still receiving a warning even after I updated to latest version -
`[FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.`

I have updated to the latest version "@fastify/static": "^5.0.0". 

I still am receiving the same error.

I have the same error with "@fastify/multipart" & "@fastify/cors". fixed with just small updated and errors are gone.

but  "@fastify/static" still giving me errors.

my **package.json**:
```
  "dependencies": {
    "@fastify/static": "^5.0.0",
    ...
    "fastify": "^3.20.2",
    ...
  },
```

### Steps to Reproduce

the basic command to run
```
npm install
npm run dev
```

Reproduced [Small Repo](https://github.com/eevan7a9/test-fastify-static) 

### Expected Behavior

I expect to no longer see the error warning after updates to "@fastify/static": "^5.0.0"

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by eevan7a9** [comment]
> 

Thank you @mcollina , I have updated the link & added a small [Repo](https://github.com/eevan7a9/test-fastify-static)

**Comment by Eomm** [comment]
You need to upgrade `fastify-swagger` as well

**Comment by eevan7a9** [comment]
🙏 thanks, do they have to be in a same version?

**Comment by Eomm** [comment]
> thanks, do they have to be in a same version?

Yes, v5 works, but it is a fluke. they are independent

**Comment by eevan7a9** [comment]
I tried `npm install @fastify/swagger@5`. but **No matching version found for @fastify/swagger@5.**

so I tried  `npm install @fastify/swagger@6`, now it's working and no more warnings 🎉

Thanks again
