### ISSUE TITLE
fastify static for fastify version 4

### ISSUE THREAD

**Issue by koanplaned** [fastify/fastify-static#331]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi all,

are you planning to enable fastify-static also for fastify version 4?

Currently I get this error message, when trying to use fastify-static 4.7.0 with fastify version 4.1.0:

```json
{
  "type": "FastifyError",
  "message": "fastify-plugin: fastify-static - expected '3.x' fastify version, '4.4.0' is installed",
  "stack": "FastifyError: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.4.0' is installed",
  "code": "FST_ERR_PLUGIN_VERSION_MISMATCH",
  "statusCode": 500
}
```

Thanks in advance for your feedback!

**Comment by Uzlopak** [comment]
Please use @fastify/static instead of fastify-static

**Comment by koanplaned** [comment]
Ah okay thanks :)
