### ISSUE TITLE
Plugin not supporting Fastify 3.x version

### ISSUE THREAD

**Issue by felipesanti** [fastify/fastify-static#341]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.2

### Plugin version

6.5.0

### Node.js version

16.8

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

I get this following error when starting the Fastify server

{"level":50,"time":1665237122422,"pid":36930,"hostname":"Felipes-MacBook-Pro.local","name":"FastifyError","code":"FST_ERR_PLUGIN_VERSION_MISMATCH","message":"fastify-plugin: @fastify/static - expected '4.x' fastify version, '3.29.2' is installed","statusCode":500,"stack":"FastifyError: fastify-plugin: @fastify/static - expected '4.x' fastify version, '3.29.2' is installed\n    at Object.checkVersion (/Users/fsanti/Development/inventrip_api/node_modules/fastify/lib/pluginUtils.js:107:63)\n    at Object.registerPlugin (/Users/fsanti/Development/inventrip_api/node_modules/fastify/lib/pluginUtils.js:121:16)\n    at Boot.override (/Users/fsanti/Development/inventrip_api/node_modules/fastify/lib/pluginOverride.js:28:57)\n    at Plugin.exec (/Users/fsanti/Development/inventrip_api/node_modules/avvio/plugin.js:80:33)\n    at Boot.loadPlugin (/Users/fsanti/Development/inventrip_api/node_modules/avvio/plugin.js:274:10)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","type":"Error","msg":"fastify-plugin: @fastify/static - expected '4.x' fastify version, '3.29.2' is installed"}

### Steps to Reproduce

node ./src/server.js --trace-warnings

### Expected Behavior

No errors

**Comment by felipesanti** [comment]
The error was caused by fastify-oas linking to a deprecated version of fastify-static

**Comment by bitdom8** [comment]
Same issue, why using older one not upgrading

fastify-plugin: fastify-static - expected '3.x' fastify version, '4.10.2' is installed

import Fastify from 'fastify';
const fastify = Fastify({ logger: true });
// import fastifyStatic from '@fastify/static';

// fastify.register(fastifyStatic, {
//   root: path.join(__dirname, 'static'),
//     // root: path.join(__dirname, 'public'),
//     prefix: '/w/',
// });
//GUN

fastify.listen({ port: 8767 }, (err, address) => {
  if (err) throw err
  // Server is now listening on ${address}
})

**Comment by kibertoad** [comment]
@bitdom8 you are using wrong dependency, switch to fastify-namespaced one

**Comment by bitdom8** [comment]
Thanks, it fixed the problem @kibertoad
