### ISSUE TITLE
Multi-root + pre-compression causes infinite loop

### ISSUE THREAD

**Issue by animecyc** [fastify/fastify-static#348]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

6.6.0

### Node.js version

16.15

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

While using the `@fastify/static` plugin with multiple configured roots and `preCompressed: true` the request for an asset that is not compressed never completes.

### Steps to Reproduce

1. Configure `@fastify/static` with the following settings: 
```javascript
{
  root: ["/path1", "/path2"],
  preCompressed: true,
}
```
3. Create two assets in `/path1` (i.e. `/path1/test1.js`, `/path1/test2.js`)
4. Gzip one of the assets in `/path1` (i.e. `/path1/test1.js.gz`)
5. Request the non-gzipped asset.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
