### ISSUE TITLE
When using "@fastify/static", it does not trigger "server.get('*')" when accessing the / path

### ISSUE THREAD

**Issue by Yberion** [fastify/fastify-static#349]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

6.6.0

### Node.js version

18.11.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

22H2 (Windows 11)

___

### Description

Hello,

I would like to use `Fastify` instead of `Express` to serve my Angular (Single Page Application) application with SSR.

I'm facing a problem when using `@fastify/static`. It seems that it is not triggering `server.get('*', ...)` when navigating to the root path, like `https://exemple.com`, however when accessing another path it is triggering it `https://exemple.com/test`.

The problem is that it is working as expected when serving a SPA with Express, when accessing root path it triggers the `server.get('*', ...)`.

This prevent me from using Fastify because it doesn't allow me to add additional logic when accessing root path.

___

I added some `console.log` in `server.get('*', ...)` and here is what happen when accessing **root path**:

### Express

![image](https://user-images.githubusercontent.com/4186385/209442081-1a62240f-1b79-4b34-a1c7-a07d6089338f.png)

### Fastify

Nothing.

![image](https://user-images.githubusercontent.com/4186385/209442107-4b3f94df-3e2e-477c-91da-3333a4665204.png)

___

If I try to access another path like `/test` (directly, or with F5), it triggers on both server as expected:

### Express

![image](https://user-images.githubusercontent.com/4186385/209442272-71ae7b91-f72c-482b-819b-9c53f41f4cac.png)

### Fastify

![image](https://user-images.githubusercontent.com/4186385/209442276-a19c06ac-c2c7-40e4-90a2-284b50b0cfc9.png)

___

If I remove the use of the plugin, it will trigger on every file and this is not the proper behavior with an SPA:

![image](https://user-images.githubusercontent.com/4186385/209442401-8485ea66-6318-49cd-97e2-df5081ad73a1.png)

Maybe I did not setup everything correctly.

___

### Steps to Reproduce

- Clone https://github.com/Yberion/Angular-SSR-Common-Engine.git
- Branche `bug/fastify-server`
- Install packages (`npm i`)

The `Express` and `Fastify` servers are in the folder `server`.
To test the behavior:

- `Fastify`: `npm run start:ssr:fastify`
- `Express`: `npm run start:ssr:fastify`

The logs should appear in the console of your IDE.

___

### Expected Behavior

Having the possibility to trigger the root path with `server.get('*', ...)` when using the static plugin else I can't use Fastify to serve my Angular application.

**Comment by mcollina** [comment]
You should set `wildcard` to `false`. 

https://github.com/fastify/fastify-static#wildcard

**Comment by Yberion** [comment]
Hello,

It is already set to `false`: https://github.com/Yberion/Angular-SSR-Common-Engine/blob/bug/fastify-server/server/fastify/server.ts#L23

**Comment by mcollina** [comment]
Note that you need two routes, one for `/*` and one for `/`

(the wildcard does not match /)

**Comment by Yberion** [comment]
I tried by declaring both routes, but it looks like `/` is already declared by the `static` plugin which is the main issue:

```ts
  server.get('/*', (req, res) => {
    const baseURL =  req.protocol + '://' + req.headers.host;
    const url = new URL(req.url, baseURL);

    console.log(baseURL);
    console.log(url);
    console.log(req.url);

    commonEngine.render({
      bootstrap: AppServerModule,
      documentFilePath: INDEX_HTML,
      url: url.href,
      providers: [{ provide: APP_BASE_HREF, useValue: baseURL }]
    })
    .then((r) => res.type('text/html').send(r))
    .catch(err => console.error(err));
  });

  server.get('/', (req, res) => {
    const baseURL =  req.protocol + '://' + req.headers.host;
    const url = new URL(req.url, baseURL);

    console.log(baseURL);
    console.log(url);
    console.log(req.url);

    commonEngine.render({
      bootstrap: AppServerModule,
      documentFilePath: INDEX_HTML,
      url: url.href,
      providers: [{ provide: APP_BASE_HREF, useValue: baseURL }]
    })
    .then((r) => res.type('text/html').send(r))
    .catch(err => console.error(err));
  });

  return server;
}
```

I'm facing this error:

```log
FastifyError [Error]: Method 'GET' already declared for route '/'
    at Object.addNewRoute (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:2037596)
    at Object.route (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:2035586)
    at Object.prepareRoute (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:2034148)
    at Object._get [as get] (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:1922279)
    at D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:1:18794
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:2114937)
    at _next (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:2115240)
    at _ZoneDelegate2.invoke (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:1814804)
    at Zone3.run (D:\GitHub\Angular-SSR-Common-Engine\dist\Angular-SSR-Common-Engine\server\fastify\main.js:7:1807089) {
  code: 'FST_ERR_DUPLICATED_ROUTE',
  statusCode: 500
}
```

**Comment by climba03003** [comment]
Seems like the folder you serve have `index.html` inside.
You may try `index: false` to disable serving index file.

**Comment by Yberion** [comment]
> Seems like the folder you serve have `index.html` inside. You may try `index: false` to disable serving index file.

Thanks for your help @climba03003, this was the right setting, `server.g('*', ...)` now catch the `/` path. 😃
