### ISSUE TITLE
setNotFoundHandler and @fastify/static context issue

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-static#354]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.11

### Plugin version

6.6.0

### Node.js version

18.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

This has been noted in https://github.com/fastify/help/issues/742, but have since encountered it myself.

Without the `prefix` option explicitly set, the `setNotFoundHandler()` function appears to inherit the context that `@fastify/static` is registered in, though this may not be the case.

### Steps to Reproduce

1. Stand up Fastify server:

```js
const fastify = require("fastify")({ logger: true });
const path = require("path");

// Import plugins
const staticPlugin = require("@fastify/static");

async function server() {
	await fastify
		.addHook("onRequest", async (req, res) => {
			res.header("x-example", "example");
		})

		.route({
			method: "GET",
			url: "/foo",
			handler: async (req, res) => {
				res.send("ok");
			},
		})

		.register(async (childContext) => {
			await childContext
				.addHook("onRequest", async (req, res) => {
					res.removeHeader("x-example");
				})
				// Register static files in public
				.register(staticPlugin, {
					root: path.join(__dirname, "public"),
					prefix: "/public/",
				})
				.route({
					method: "GET",
					url: "/bar",
					handler: async (req, res) => {
						res.send("ok");
					},
				});
		});

	await fastify.listen({ port: 8000 });
}

server();
```

2. Make GET request to `/public/404` and `/404`:
    - The x-example header is removed for  `/public/404`, as expected
    - x-example header remains for `/404`, as expected
4. Remove or comment out the `prefix: "/public/",` line, and restart the server
5. Make GET request to `/public/404` and `/404`:
    - The x-example header is removed for  `/public/404`, **NOT expected** as the `/public/` prefix has gone, so expected the main context to handle this
    - x-example header is removed for `/404`, **NOT expected**, as above

### Expected Behavior

As above, expected that child context's header changes do not impact a 404 response.

**Comment by mcollina** [comment]
I don't think this is a bug but a consequence of how the wildcard that this module adds: https://github.com/fastify/fastify-static/blob/8dab6ec5c4525cbe132ec1b7863d884392288406/index.js#L321-L326.

In other terms, the wildcard is matching your request and call the notfound logic: because the wildcard matched, the hook has run. I think we should document this better.

The solution to this problem is to set wildcard: false.

**Comment by Fdawgs** [comment]
Brilliant, thanks @mcollina, completely missed that option in the docs. 😬
