### ISSUE TITLE
Parameter in route and serving files

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-static#356]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian 11

### Description

Setting fastify-static prefix to '/' and using of parameter isn't working. It's not only with a single parameter, you can also use multiple parameters in route, the main problem is setting '/' as prefix in fastify-static. You will never be able to access image or other files ´.

http://127.0.0.1:3000/testUrl - serve OK
http://127.0.0.1:3000/image.png - serve OK

Is that possible to make accessing the image.png to serve the image.png and not the response from the route?

### Steps to Reproduce

```const path = require('path');
const fastify = require('fastify')();

fastify.register(require('@fastify/static'), {
  root: path.join(__dirname, 'public'),
  prefix: '/'
});

fastify.get('/:a', (req, res) => {
  return res.send('OK');
});

fastify.listen({ port: 3000 }, (err, address) => {
  if (err) throw err;
});
```

**Comment by yaneony** [comment]
Adding subfolders, for example /public/images and putting image.png there will conflict also with routes like /:a/:b ...

**Comment by mcollina** [comment]
You should set `wildcard: false`.
