### ISSUE TITLE
Support URL for root parameter (and `file:` protocol)

### ISSUE THREAD

**Issue by saschanaz** [fastify/fastify-static#364]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

For now it must be string or array of strings, but modern Node.js also supports URL for many APIs. It would be great to support it here too.

### Motivation

`root: new URL(".", import.meta.url)` (or `.toString()`) fails because neither of URL nor `file:` protocol is supported. `fileURLToPath` is always required.

### Example

```js
fastify.register(fastifyStatic, {
  root: new URL("assets/", import.meta.url)
});
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by AmishBaztard** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Where is the register method created? I'm gonna look into tackling this.

**Comment by saschanaz** [comment]
I guess something around here should be modified to either:

https://github.com/fastify/fastify-static/blob/ef4125b799c33c8593ee8cf36713b882a02a8171/index.js#L17

1. Just allow URLs as-is (but check they are `file:`)
2. Normalize URLs into strings

I'm not sure 1 is safe because the other dependency seemingly only accepts string too. 
4.

**Comment by AmishBaztard** [comment]
> 

You're saying for 2. to just convert URL objects to strings? `URL.toString()`? That seems awfully quick of a fix. Just check if its type is URL and convert.

**Comment by saschanaz** [comment]
fileURLToPath should be used because toString will generate file: protocol which is not supported either.

**Comment by AmishBaztard** [comment]
@mcollina I've made this change but I can't make a pull request, I think I need to be assigned?

**Comment by saschanaz** [comment]
You should be able to, do you see any error?

**Comment by AmishBaztard** [comment]
> You should be able to, do you see any error?

Nada, I got it. Hey, was the goal here to only support URL with the `file` protocol? Or any URL types?
