### ISSUE TITLE
inflight - transient dependency introduced memory leak

### ISSUE THREAD

**Issue by jorgemlopez** [fastify/fastify-static#423]
## 👮 Responsible Disclosure

Do not open issues that might have security implications. It is critical that security related issues
are reported privately so we have time to address them before they become public knowledge.

Please read our [SECURITY.md](https://github.com/fastify/.github/blob/main/SECURITY.md) before reporting a vulnerability.

Individuals who find potential vulnerabilities in a package are invited
to complete a vulnerability report on the dedicated HackerOne organization:

[https://hackerone.com/fastify](https://hackerone.com/fastify)

Vulnerabilities can also be reported by emailing to Fastify core members: 

- [Matteo Collina](mailto:matteo.collina@gmail.com)

### Summary
This package uses a version of [node-glob](https://github.com/isaacs/node-glob) which uses as a dependency [inflight](https://github.com/isaacs/inflight). The version of inflight uses has a memory leak. See issue: https://github.com/isaacs/inflight/issues/18.

![Screenshot 2023-12-04 at 1 14 23 PM](https://github.com/nestjs/serve-static/assets/39564329/710e1085-432d-4c7a-8872-61ebf131ca88)

Inflight seems to have been abandoned and it is not longer a dependency of node-glob version 9 and above. However @nestjs/static is not compatible with node-glob v9+. 

### Proposed Resolution
To fix this, you will need to use fast-glob or upgrade the dependency to glob v9 where the dependency on inflight has been removed.

**Comment by jorgemlopez** [comment]
@mabreuortega for visibility

**Comment by gurgunday** [comment]
Version 9 only supports node 16+ and (AFAIK) it contains a blue-oak–licensed dependency

**Comment by gurgunday** [comment]
We might need to fork...

**Comment by Uzlopak** [comment]
Reading the sec vuln report it seems to be just non issue.

> Memory Leak: inflight is vulnerable to a Memory Leak. The vulnerability is due to lack of restrictions on how many callbacks the library can concurrently support, which can result in a NodeJS out of heap memory crash.

**Comment by jorgemlopez** [comment]
Snyk is reporting it as a [High Risk issue](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) based on:

https://cwe.mitre.org/data/definitions/772.html

https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H

This is all based on this original issue: https://github.com/isaacs/inflight/issues/5

**Comment by epignosisx** [comment]
Leaving this here for inspiration:

https://github.com/mcollina/help-me/pull/19

**Comment by mcollina** [comment]
If you land yourself here, don't worry: this module does not suffer from a memory leak, as the call to glob is used only once during startup.
