### ISSUE TITLE
Correct module exports?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-static#430]
In `fastify-cors`, the [plugin wrapped inside `fastify-plugin` is exported](https://github.com/fastify/fastify-cors/blob/034bb137794575d59243608f2082b72f7a314fa7/index.js#L305-L307) for all three export types (CJS, ESM, TS).

However, for `fastify-static` it is [only wrapped inside `fastify-plugin` for the CJS export](https://github.com/fastify/fastify-static/blob/master/index.js#L556-L561).

What determines how we export it?

**Comment by mcollina** [comment]
They are identical. fastify-plugin  adds a property and returns the function.

**Comment by Fdawgs** [comment]
> They are identical. fastify-plugin  adds a property and returns the function.

Gotcha, thanks @mcollina!
