### ISSUE TITLE
`FST_ERR_REP_ALREADY_SENT` when wrapping route handler

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [fastify/fastify-static#434]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.0

### Plugin version

7.0.0

### Node.js version

20.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.6.1

### Description

When using with `@autotelic/fastify-opentelemetry` including the `wrapRoutes` option, requests for the statics result in an empty response and a `FST_ERR_REP_ALREADY_SENT` error.

### Steps to Reproduce

I've pushed up a repo with the steps to reproduce and further details https://github.com/10xLaCroixDrinker/fastify-static-issue

**Comment by climba03003** [comment]
My suggestion is remove the `async` from `@autotelic/fastify-opentelemetry`.
So, it will respect the original function.

**Comment by 10xLaCroixDrinker** [comment]
> I am closing this issue because nothing show the bug is exist inside this repository. Please minimize your reproducible snippet without any other plugins.

Does the proposed solution not show that?

**Comment by climba03003** [comment]
> Does the proposed solution not show that?

Consider the follow code working properly without `@autotelic/fastify-opentelemetry`.
You should not force everyone to use `async` or return `Promise`.

```js
instance.get('/ok', function(request, reply) {
  setTimeout(function() {
    reply.send('ok')
  }, 1000)
})
```

**Comment by 10xLaCroixDrinker** [comment]
Thanks for your help @climba03003. I opened a PR to `@autotelic/fastify-opentelemetry`.
