### ISSUE TITLE
404 when using wildcard

### ISSUE THREAD

**Issue by TheDirigible** [fastify/fastify-static#438]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3

### Plugin version

7

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

This serves my index.html as expected:
        fastify.register(fastifyStatic, { prefix:'/tmp', root:'/www/root', wildcard:false })
This causes 404:
        fastify.register(fastifyStatic, { prefix:'/tmp', root:'/www/root', wildcard:true })
I want to use wildcard, to support new files.  What's the problem?  Not sure why wildcard would break this

I did some debugging, and it seems that when you call fastify.get('/tmp*') the handler is never called when the route is just '/tmp'.  The * prevents it from reaching the handler.  
It seems you need to do both:
fastify.get('/tmp/')
and
fastify.get('/tmp/*')

### Steps to Reproduce

na

**Comment by gurgunday** [comment]
Can you try the prefix: /tmp/

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by gurgunday** [comment]
Pretty sure it’s the prefix - as shown in the docs, it has to be prepended with a slash

Closing, but feel free to comment if that doesn’t resolve your problem
