### ISSUE TITLE
Is there a way to reduce the size of importing @fastify/static?

### ISSUE THREAD

**Issue by jebarpg** [fastify/fastify-static#443]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I see that @fastify/static takes up 109.2k and when gzipped its 35.2k, is there a way to only import the parts which I am using to reduce the size of my project?

Here is a sample code I'm using:

```
  // Register the static public directory
  server.register(fastifyStatic, {
    root: path.join(process.cwd(), './public'), 
  });

  // Register the static docs directory
  server.register(fastifyStatic, {
    root: path.join(process.cwd(), './docs'),
    prefix: '/docs/',
    decorateReply: false, 
  });
```

Sorry if this has already been asked, I did searches on reduce size, import size etc in the closed and open issues. Nothing came up that I could see.

Thanks in advance for taking the time to help.
Cheers!

**Comment by climba03003** [comment]
I believe you embedded the `example` and `test` folder, you can delete it to reduce the size.
Those folders exists in `npm` registry because we would like to deliver the package source as is.
