### ISSUE TITLE
How can I enable Gzip in Fastify-static

### ISSUE THREAD

**Issue by avilang** [fastify/fastify-static#45]

**Comment by usopan** [comment]
I am using the same but on browser request end is not being set properly. Request response time on browser shows 5s but in trace logs of fastify it show request completed within few ms.

PS I am not using any proxy to run this test. and if I remove compression response time is as expected.

**Comment by mcollina** [comment]
Can you upload an example to reproduce? Thanks.

**Comment by usopan** [comment]
https://github.com/fastify/fastify-static/issues/52

**Comment by PierBover** [comment]
If anyone stumbles upon this as I did... you need to register the `fastify-compress` global hook before registering `fastify-static`.

```
fastify.register(require('fastify-compress'));

fastify.register(require('fastify-static'), {
	root: path.join(__dirname, 'public'),
	prefix: '/public/'
});
```
Otherwise responses of static files won't be compressed.
