### ISSUE TITLE
Plugin overwrites existing `content-type` header

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-static#480]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

8.0.2

### Node.js version

20.18.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description
v8.x does not respect existing `content-type` headers when serving files and [overwrites them here](https://github.com/fastify/fastify-static/blob/1b0386ff8fd9035feb3d98a329a10d6a8dacba0b/index.js#L361) using headers returned by a `@fastify/send` call. This was not the case in previous versions of the plugin.

Spotted this as I set the content-type of a static file [using `reply.type()` here](https://github.com/Fdawgs/docsmith/blob/fd17e8538f95d856e7ed1ca06bc9066d52a2a27c/src/routes/docs/index.js#L61-L62), and it's overwriting it.

### Expected Behavior

For the plugin to check if `content-type` is already set, and use it if so.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
