### ISSUE TITLE
docs: update the README to state that this plugin support fastify 5

### ISSUE THREAD

**Issue by SafetZahirovic** [fastify/fastify-static#485]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Update readme to reflect support for fastify 5. Support for v5 came with 8.0.0 release

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue?

**Comment by SafetZahirovic** [comment]
@Eomm i need some permissions to push the code :) 

`Permission to fastify/fastify-static.git denied to SafetZahirovic.`

Can you give me the access?

**Comment by jsumners** [comment]
> Can you give me the access?

No. Read https://jrfom.com/posts/2017/03/08/a-primer-on-contributing-to-projects-with-git/

**Comment by exrhizo** [comment]
I wonder fastify-stop stopped supporting 4.x

**Comment by SafetZahirovic** [comment]
@jsumners thank you 🙏🏼

Sorry for the delay om pr, I am currently traveling. 

@exrhizo the support for 5.x started in version 8.0.0. I had to track down commit to find when the change was made. 

But there is no tree for 7.x or lower until 5.x, so it’s a bit difficult to update readme and to point it to the correct tree.

**Comment by climba03003** [comment]
> I wonder when fastify-stop stopped supporting 4.x ...

official plugins follows the EoL of the `fastify`.
https://fastify.dev/docs/latest/Reference/LTS/
![image](https://github.com/user-attachments/assets/7e96e9dd-203d-41dd-82b0-d7d03a3cc41d)

**Comment by Ankush1oo8** [comment]
I want to change it but do not know what to change exactly

**Comment by Ankush1oo8** [comment]
please check the PR #487 I have tried to fix this issue and made some changes in readme file
