### ISSUE TITLE
Reloading a static page served by fastify-static gets stuck

### ISSUE THREAD

**Issue by jinwoo** [fastify/fastify-static#50]
In my test app, which simply uses `fastify-static` for serving `index.html` and some css files, etc, the page loads fine the first time. But pressing the reload button gets stuck. Chrome just shows the spinner on the tab, displaying nothing. It looks like the `index.html` file is served fine but requests for all other resources are pending forever.

If I clear the cache and the cookies, the page loads again fine. But only the first time. The same issue afterwards.

My env:
* fastify: 1.0.0
* fastify-static: 0.10.0
* using http2 with `tls-keygen`-generated certificates

**Comment by mcollina** [comment]
Do you have a repro script just with fastify-static? So it might be related to 304s and cached files?

**Comment by jinwoo** [comment]
Yes, the fastify-auto-push's sample app: https://github.com/google/node-fastify-auto-push/tree/master/samples/static-page

If you specify the `--http2` flag but NOT the `--auto-push` flag, the app will just use `fastify-static`.
