### ISSUE TITLE
Using fastify-compression breaks Response time for static assets on browser

### ISSUE THREAD

**Issue by usopan** [fastify/fastify-static#52]
Config 
`fastify.register(require('fastify-compress'), { threshold: 0 });`
`fastify.register(fastifyStatic, __PROD__ ? {
    root: path.resolve(path.join(__dirname, '/../', 'public')),
    prefix: '/public/',
    setHeaders: function (res, path, stat) {
      res.setHeader('Content-Encoding', 'gzip')
      // console.log(stat)
    }
  } 
`
tracelog on server 
`{"level":30,"time":1524127887660,"msg":"incoming request","pid":11241,"hostname":"utkarsh-Lenovo-ideapad-300-15ISK","reqId":9,"req":{"id":9,"method":"GET","url":"/public/assets/15_e8d859185f2e2b063a5c.js","remoteAddress":"127.0.0.1","remotePort":37776},"v":1}`
`{"level":30,"time":1524127887668,"msg":"request completed","pid":11241,"hostname":"utkarsh-Lenovo-ideapad-300-15ISK","reqId":9,"res":{"statusCode":200},"responseTime":7.410842999815941,"v":1}
`

Browser 
![image](https://user-images.githubusercontent.com/4994952/38982423-70cbf782-43df-11e8-919a-c0c7c0493152.png)

PS  Request is being made on localhost and if I remove compression it works properly but without compression ofcourse.

**Comment by mcollina** [comment]
Which version of fastify, fastify-static, fastify-compress are you using?

**Comment by mcollina** [comment]
Can you please upload a __full example__?

**Comment by mcollina** [comment]
Fixed in fastify-compress 0.6.0.
