### ISSUE TITLE
Server Side Caching

### ISSUE THREAD

**Issue by usopan** [fastify/fastify-static#54]
Hi, 
Is there any way to configure a server side caching of static assets?
Using something like fastify-caching.
PS: I have deployed fastify using docker containers so I cannot rely on iobuffer performance as it is being shared by multiple apps.

**Comment by mcollina** [comment]
This would be a very interesting feature, but it's currently not supported.
The tricky part is that this logic should go into http://npm.im/send instead, as it's there that the caching headers are computed.

**Comment by aalfiann** [comment]
@usopan I guess it is better to use reverse proxy or varnish.
