### ISSUE TITLE
Inability to serve multiple prefixed root URL's

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify-static#62]
For a development server I'm working on I tried the following:
```js
const path = require('path');
const fastify = require('fastify')();
const fastifyStatic = require('fastify-static');

fastify.register(fastifyStatic, {
	root: path.join(__dirname, 'node_modules'),
	prefix: '/node_modules/',
});

fastify.register(fastifyStatic, {
	root: path.join(__dirname, 'html/myapp'),
	prefix: '/myapp/',
});
```

This causes an exception from node_modules/fastify/lib/decorate.js:38:
`Error: The decorator 'sendFile' has been already added to Reply!`

Is it possible to fix this within `fastify-static` or should I write my own middleware that uses `send` directly?

**Comment by allevo** [comment]
Nice catch! Thanks! 

This is a bug. Would you mind to send a PR?

**Comment by coreyfarrell** [comment]
I've created an option with docs and a test to ensure this can be dealt with, I don't think it can be fixed another way.

**Comment by delvedor** [comment]
> This is a bug.

Nope, this is the correct behavior of the API, you are adding multiple times the same decorator.

I'll release very soon the new version of Fastify, which will have `hasReplyDecorator`, so we can check it directly inside `fastify-static` if a specific decorator has already been added.

In any case, the main issue will be that a user will get an "unpredictable" behavior from `reply.sendFile` because it will work only for the first registered static plugin.

The best solution would be register the two instances of `fastify-static` in two different plugins (which is the main idea behind the Fastify's plugin architecture), in this way there will be no conflicts.

```js
// first plugin
fastify.register((instance, opts, next) => {
  instance.register(require('fastify-static'), {
	root: path.join(__dirname, 'node_modules'),
	prefix: '/node_modules/'
  })
  // here `reply.sendFile` refers to 'node_modules' files
  next()
})

// second plugin
fastify.register((instance, opts, next) => {
  instance.register(require('fastify-static'), {
	root: path.join(__dirname, 'html/myapp'),
	prefix: '/myapp/'
  })
  // here `reply.sendFile` refers to 'html/myapp' files
  next()
})
```

**Comment by mcollina** [comment]
Another alternative is to provide an option to avoid sendFile being added.
Il giorno dom 20 mag 2018 alle 12:29 Tomas Della Vedova <
notifications@github.com> ha scritto:

**Comment by coreyfarrell** [comment]
#63 adds an option to disable the reply decorator per instance of `fastify-static`.  This allows `fastify-static` to be added multiple times in the same plugin context but requires explicitly choosing no more than one to provide `reply.sendFile`.  I'm aware you can put each `fastify-static` into a separate plugin context but then you don't get `reply.sendFile` in the global context.  I saw `hasReplyDecorator` in the code, decided this was the wrong solution for this module since each `reply.sendFile` can have different settings so the conflict must be resolved explicitly.
```js
// first plugin
fastify.register((instance, opts, next) => {
  instance.register(require('fastify-static'), {
	root: path.join(__dirname, 'node_modules'),
	prefix: '/node_modules/'
  })
  // here `reply.sendFile` refers to 'node_modules' files
  next()
})

// second plugin
fastify.register((instance, opts, next) => {
  instance.register(require('fastify-static'), {
	root: path.join(__dirname, 'html/myapp'),
	prefix: '/myapp/'
  })
  // here `reply.sendFile` refers to 'html/myapp' files
  next()
})

// here `reply.sendFile` is undefined.
```

**Comment by delvedor** [comment]
> decided this was the wrong solution

@coreyfarrell please moderate your tone, an aggressive behavior is not welcomed.

**Comment by FishOrBear** [comment]
This information should be extracted from the document or README.

**Comment by rauschma** [comment]
If there is time, it’d be nice to have the official solution documented in the readme (I’m not completely sure which one it is).

I’d also find it useful if it were possible to merge multiple local directories into the same online directory. Local directories that are mentioned later would provide fallbacks for earlier local directories.

**Comment by mcollina** [comment]
@rauschma would you mind to open an issue about this "merging" functionality? I don't know see how that could work.
