### ISSUE TITLE
Can no longer use the catch all route

### ISSUE THREAD

**Issue by aunz** [fastify/fastify-static#64]
```js
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'public'),
})

// the catch all route below will never be called 😥
fastify.get('*', function (request, reply) {
  console.log('Catch all')
  reply.send('*')
})
```

**Comment by mcollina** [comment]
This is expected. What do you want to achieve?

The routing of fastify is deterministic, fastify-static does not know which files are on disk so we can only specify a wildcard route. If you need this, you will have to add a prefix to fastify-static option,

**Comment by aunz** [comment]
Thanks @mcollina 
It's for creating single page apps, similar to the [express-history-api-fallback](https://www.npmjs.com/package/express-history-api-fallback)
So users can go to any route and the routing is done on client side

**Comment by mcollina** [comment]
This is a bug. I think we should refactor this module in two: fastify-send-file and fastify-static.

@delvedor what do you think?

**Comment by delvedor** [comment]
I would like to see if we can ad an option to disable the catch all route and expose just the decorator, more or less the same of what we are doing in [fastify-swagger](https://github.com/fastify/fastify-swagger).

**Comment by neosiae** [comment]
Any updates on this?

**Comment by buzzeins** [comment]
hmm, still the same issue...
"fastify": "^2.10.0",
"fastify-static": "^2.5.0",
