### ISSUE TITLE
Add some TypeScript typings 

### ISSUE THREAD

**Issue by yuriy-yarosh** [fastify/fastify-static#66]
It would be great to add some mbed typescript typings, like fastify [did](https://github.com/fastify/fastify/blob/master/fastify.d.ts).

**Comment by delvedor** [comment]
Yes, it would be nice!
Would you like to send a pr?

**Comment by yuriy-yarosh** [comment]
Sure, np.
Will impl one today.

**Comment by jannikkeye** [comment]
@mcollina can we please close this? Typings exist on definitelytyped in accordance with the fastify docs. We should also close all the other issues opened in the other repositories as those changes are not needed.

**Comment by mcollina** [comment]
In the fastify org, we typically keep the typings within the modules themselves. So, I'd still like to get a PR to add typings to this module.

**Comment by jannikkeye** [comment]
Ah, all right, then I'll have a look.

**Comment by jannikkeye** [comment]
@mcollina maybe that should be specifically mentioned in the docs under Plugin Types. A while back when I was authoring types for other plugins it seemed the consensus was to host plugins in DefinitelyTyped. This also seems to be the case when reading the docs.

**Comment by mcollina** [comment]
@jannikkeye Would you mind to send a PR to the docs?

**Comment by jannikkeye** [comment]
@mcollina not at all I'll get on it.
