### ISSUE TITLE
Feature Request: Add the ability to serve a folder directly from the terminal

### ISSUE THREAD

**Issue by bjdash** [fastify/fastify-static#73]
It should have the ability to serve a folder directly from the terminal.

For example: 
Lets say I installed fastify-static globally with `-g` flag, now I should be able to serve a folder with below commant
`fastify-static .   //serve current folder`
`fastify-static app/public/ -p 80   //serve the folder app/pblic on post 80`

**Comment by nwoltman** [comment]
@bjdash An example of a CLI tool that already does this is the [`http-server`](https://www.npmjs.com/package/http-server) package.
