### ISSUE TITLE
HTTP2 / Connection refused / 304 response

### ISSUE THREAD

**Issue by peterschmiz** [fastify/fastify-static#76]
I recently started to use Fastify to have http2 support.

I just noticed if I reload my browser with caching enabled (so not using Chrome DevTools 'Disable Cache' option) almost every time I have a "Connection refused / 304" error and my asset is not loaded.

I'm running it on localhost now, using a self-signed certificate, added the certificate as an Always Trusted cert. I'm using Chrome 70.0.3538.110 on OSX.

![image](https://user-images.githubusercontent.com/2334176/48870047-93534d00-eddf-11e8-9ffb-826c7c664832.png)

Once I turn off the http2 in Fastify everything works fine.

![image](https://user-images.githubusercontent.com/2334176/48870073-a8c87700-eddf-11e8-8f99-1ef59b6796e5.png)

I was wondering if could it be because http2 push is used? I was trying to simply have http2 protocol and static asset serving, i can live without http2 push. (it show the same symptoms as the `node-auto-push`, which I tried before `fastify-static`)

I have this error (using pm2) in the logs:

```bash
TypeError: Cannot read property 'Symbol(trailers)' of undefined
  at ServerHttp2Stream.onStreamTrailersReady (internal/http2/compat.js:377:36)
  at ServerHttp2Stream.emit (events.js:182:13)
  at Http2Stream.onStreamTrailers [as ontrailers] (internal/http2/core.js:311:15)
```

My index.js looks like this (removed unnecessary parts):

```javascript

const fastify = require('fastify')({
  logger: {
    prettyPrint: DEBUG,
  },
  trustProxy: false,
  http2: true,
  https: {
    allowHTTP1: true,
    key: fs.readFileSync(path.join(__dirname, '.', 'https', SSLKey)),
    cert: fs.readFileSync(path.join(__dirname, '.', 'https', SSLCert)),
  },
});

const helmet = require('fastify-helmet');
const fastifyPug = require('fastify-pug');

const assetRoot = path.join(__dirname, '..', 'client', 'assets');

fastify.register(require('fastify-static'), {
  root: assetRoot,
});

fastify.register(require('fastify-compress'), {
  global: true,
});

fastify.register(helmet, {
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ['\'self\''],
      styleSrc: ['\'self\'', '\'unsafe-inline\''],
      scriptSrc: ['\'self\'', '\'unsafe-inline\''],
    },
  },
  featurePolicy: {
    features: {
      fullscreen: ['\'none\''],
      payment: ['\'none\''],
      syncXhr: ['\'none\''],
      microphone: ['\'none\''],
    },
  },
  frameguard: {
    action: 'deny',
  },
  hidePoweredBy: { setTo: 'Sun and love <3' },
  referrerPolicy: { policy: 'same-origin' },
});
fastify.register(fastifyPug, { views: `${path.join(__dirname)}/views` });

fastify.get('/', (request, reply) => {
  reply
    .code(200)
    .render('index.pug');
});

fastify.listen(SECUREPORT, HOST, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```
I'm stuck now, but really don't want to revert to http1.1 or to manually serve assets.
Can the Node 10 and its experimental http2 feature the cause?

Thanks!

**Comment by nwoltman** [comment]
@peterschmiz I was not able to reproduce this bug locally using the code you provided (Node `10.13.0`). Would you be able to create a test repo with the minimum amount of code needed to reproduce the bug?

Also, `fastify-static` doesn't use HTTP/2 push so that shouldn't be the cause of this bug. From the looks of it, this might be an issue with Node core.

**Comment by peterschmiz** [comment]
@nwoltman many thanks! It was the Node core indeed! I just had to update it and now the error is gone! It has nothing to do with `fastify-static`, so sorry for the issue!

**Comment by mcollina** [comment]
No worries! Happy to help!
