### ISSUE TITLE
setNotFoundHandler is broken with Fastify v2

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify-static#77]
I checked a bit and couldn't understand what the problem might be. I played around with the tests of `setNotFoundHandler` in main Fastify repo and they seem to be good. 

Any ideas what might be wrong?

https://github.com/fastify/fastify-static/blob/master/test/static.test.js#L362

```
  not found responses can be customized with fastify.setNotFoundHandler() > /path/does/not/exist.html
  not ok should be equal
    +++ found
    --- wanted
    -text/plain
    +application/json; charset=utf-8
    compare: ===

  not found responses can be customized with fastify.setNotFoundHandler() > /path/does/not/exist.html
  not ok should be equal
    +++ found
    --- wanted
    -/path/does/not/exist.html Not Found
    +{"statusCode":404,"code":"ENOENT","error":"Not Found","message":"ENOENT: no such file or directory, stat 'C:\\Users\\cemre.mengu\\Desktop\\fastify-static\\test\\static\\path\\does\\not\\exist.html'"}
    compare: ===
```

**Comment by mcollina** [comment]
I don’t understand. Are you seeing test failures? Can you craft an example that reproduces the problem you are experiencing?

**Comment by cemremengu** [comment]
It didnt pass from citgm as posted so I wanted to check. Yes, they are test failures. If you run tests with Fastify v2 you can see that it fails.
