### ISSUE TITLE
Add beforeHandle support for auth

### ISSUE THREAD

**Issue by liuwill** [fastify/fastify-static#81]
if we can add some beforeHandle support, so we could use basic auth for static content only

**Comment by nwoltman** [comment]
I believe you can already do this by registering `fastify-static` inside a scoped plugin:

```js
fastify.register(function (fastify, opts, next) {
  // Register your auth plugin or add your auth hooks here

  fastify.register(require('fastify-static'), {
    // fastify-static options
  })

  next()
})
```

**Comment by liuwill** [comment]
In my case, I only want to add auth plugin for static file. the other route will never be limited

**Comment by mcollina** [comment]
You can you achieve exactly that with the syntax above.

**Comment by liuwill** [comment]
It works, Thanks
