### ISSUE TITLE
Type link directly return 404 error

### ISSUE THREAD

**Issue by galuh1300d** [fastify/fastify-static#87]
I've error when i typed my link directly like this localhost:5000/katalog, it send me error 404. But if i move from link to link using <Link> (React Router Dom) it doesn't show me error.
Here's my screen recorder of this behaviour [Youtube Video.](https://youtu.be/lYe3grlH2Yc)
Why this happened?

**Comment by cemremengu** [comment]
It is hard to tell with just this but keep in mind that browser sends a GET request. What does your route look like?

**Comment by galuh1300d** [comment]
`if (process.env.NODE_ENV === 'production') {
    fastify.register(require('fastify-static'), {
        root: path.join(__dirname, 'client/build')
      })
      
    fastify.get('*', function (req, reply) {
        reply.sendFile('index.html')
    })
}`

i just render static html file, routing is in react side

**Comment by cdiezmoran** [comment]
Currently facing the same problem, did you find a fix? @galuh1300d
