### ISSUE TITLE
How to use a Layout ?

### ISSUE THREAD

**Issue by xyz-mtl** [fastify/fastify-static#89]
Hi,
I would like to know if it's possible to use a Layout with Fastify-Static.
- Every page have the same header
- Every page have the same footer
- Every page have the same style and layout

Can you share a solution or it's not possible ?

Thank you

**Comment by StarpTech** [comment]
Hi @xyz-mtl your question has nothing to do with `fastify-static`. I think you are looking for a template plugin. You can use the fastify plugin [point-of-view](https://github.com/fastify/point-of-view).

**Comment by xyz-mtl** [comment]
@StarpTech 👍
