### ISSUE TITLE
Option to redirect requests for directory.

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify-static#92]
Take the following files within the root directory:

    index.html
    sub/index.html

Configure fastify-static to include `index: 'index.html'`.  In this case `http://localhost/` serves the root `index.html`, `http://localhost/sub/` serves `sub/index.html`.  But `http://localhost/sub` is a 404 error.  Would you accept an option that would hook `send.on('directory')` to perform a 301 redirect of such requests to the path including the trialing slash?  Such that `http://localhost/sub` would be 301 with `Location: http://localhost/sub/`.  I haven't tested this yet but the `send` [documentation](https://github.com/pillarjs/send#serving-from-a-root-directory-with-custom-error-handling) tells how to accomplish this.  I'm assuming that directory redirects would need to be opt-in rather than opt-out?  Either would be fine with me, just figured I'd ask since fastify-static is in the middle of a semver-major release.

**Comment by mcollina** [comment]
Yes, send a PR against master. I think it would be better if it was opt-in. What is the default behavior of express in this case?

**Comment by coreyfarrell** [comment]
Looks like it's opt-out for express https://github.com/expressjs/serve-static#redirect.  I'm indifferent to opt-in vs opt-out, just would like the ability to have the functionality without explicitly creating a redirect for each directory.  Since you've already expressed a preference for opt-in I'll start the code based on that, switching won't be difficult if desired.

**Comment by mcollina** [comment]
That behavior would match the default of fastify +1. See this for details: https://github.com/fastify/fastify/blob/master/docs/Server.md#ignoretrailingslash.

**Comment by coreyfarrell** [comment]
I've posted a PR including tests.  Worth noting I was unable to get this working for `wildcard === false`.  I've documented the incompatibility, I'm not sure how to resolve this (if it can be resolved).  Maybe `ignoreTrailingSlash` would make `wildcard === false && redirect === true` work?
