### ISSUE TITLE
fastify-static latest = 2.3.2

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify-static#98]
Sorry to ping you right away but it looks like fastify-static@2.3.2 was accidentally published to npm tag `latest` instead of `next`.  Just got an alert via greenkeeper about a build that failed with fastify@1.x + fastify-static@2.3.2.

CC @cemremengu

**Comment by cemremengu** [comment]
@coreyfarrell fixed. Apologies for breaking things :(
